package cn.iocoder.yudao.module.erp.dal.mysql.finance.receivable;

import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.yudao.module.erp.controller.admin.finance.receivable.vo.account.ErpReceivableAccountPageReqVO;
import cn.iocoder.yudao.module.erp.dal.dataobject.finance.receivable.ErpReceivableAccountDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

@Mapper
public interface ErpReceivableAccountMapper extends BaseMapperX<ErpReceivableAccountDO> {

    @Select({
            "<script>",
            "SELECT c.id AS customerId,",
            "       c.name AS customerName,",
            "       c.contact AS contact,",
            "       c.mobile AS mobile,",
            "       c.area_id AS areaId,",
            "       c.customer_type AS customerType,",
            "       c.sale_user_id AS saleUserId,",
            "       u.nickname AS saleUserName,",
            "       c.dept_id AS deptId,",
            "       d.name AS deptName,",
            "       c.route_id AS routeId,",
            "       IFNULL(ext.base_amount, 0) AS baseAmount,",
            "       c.credit_limit AS creditLimit,",
            "       c.credit_term_days AS creditTermDays,",
            "       IFNULL(so.saleOutAmount, 0) AS saleOutAmount,",
            "       IFNULL(sr.saleReturnAmount, 0) AS saleReturnAmount,",
            "       IFNULL(pa.priceAdjustAmount, 0) AS priceAdjustAmount,",
            "       IFNULL(rc.receiptAmount, 0) AS receiptAmount,",
            "       IFNULL(wo.writeOffAmount, 0) AS writeOffAmount,",
            "       IFNULL(ro.otherReceivableAmount, 0) AS otherReceivableAmount,",
            "       IFNULL(ext.advance_amount, 0) AS preAdvanceAmount,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) AS receivableAmount,",
            "       IFNULL(rc.receiptAmount, 0) + IFNULL(wo.writeOffAmount, 0) AS receivedAmount,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) AS unreceivedAmount,",
            "       '应收账款' AS billType,",
            "       CASE WHEN IFNULL(rc.receiptAmount, 0) + IFNULL(wo.writeOffAmount, 0) = 0 THEN '未收款'",
            "            WHEN IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) > 0 THEN '部分收款'",
            "            ELSE '已收款' END AS receiveStatus,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) AS receivableBalance,",
            "       CASE WHEN c.credit_limit IS NULL THEN NULL ELSE c.credit_limit - (IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0)) END AS creditBalance,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) + IFNULL(ext.advance_amount, 0) AS totalReceivable,",
            "       lastBiz.lastBizTime AS lastBizTime",
            "  FROM erp_customer c",
            "  LEFT JOIN system_users u ON u.id = c.sale_user_id",
            "  LEFT JOIN system_dept d ON d.id = c.dept_id",
            "  LEFT JOIN erp_customer_extend_info ext ON ext.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, SUM(total_price) AS saleOutAmount, MAX(out_time) AS lastBizTime",
            "         FROM erp_sale_out",
            "        WHERE deleted = 0 AND status = 20",
            "          <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR sale_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND sale_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if>",
            "          <if test='reqVO.startTime != null and reqVO.endTime != null'>",
            "          AND out_time BETWEEN #{reqVO.startTime} AND #{reqVO.endTime}",
            "          </if>",
            "        GROUP BY customer_id",
            "  ) so ON so.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, SUM(total_price) AS saleReturnAmount",
            "         FROM erp_sale_return",
            "        WHERE deleted = 0 AND status = 20",
            "          <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR sale_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND sale_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if>",
            "          <if test='reqVO.startTime != null and reqVO.endTime != null'>",
            "          AND return_time BETWEEN #{reqVO.startTime} AND #{reqVO.endTime}",
            "          </if>",
            "        GROUP BY customer_id",
            "  ) sr ON sr.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, SUM(total_adjust_price) AS priceAdjustAmount, MAX(adjust_date) AS lastBizTime",
            "         FROM erp_sale_price_adjust",
            "        WHERE deleted = 0 AND status = 20",
            "          <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR adjust_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND adjust_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if>",
            "          <if test='reqVO.startTime != null and reqVO.endTime != null'>",
            "          AND adjust_date BETWEEN #{reqVO.startTime} AND #{reqVO.endTime}",
            "          </if>",
            "        GROUP BY customer_id",
            "  ) pa ON pa.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, SUM(total_price) AS receiptAmount, MAX(receipt_time) AS lastBizTime",
            "         FROM erp_finance_receipt",
            "        WHERE deleted = 0 AND status = 20",
            "          <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR finance_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND finance_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if>",
            "          <if test='reqVO.startTime != null and reqVO.endTime != null'>",
            "          AND receipt_time BETWEEN #{reqVO.startTime} AND #{reqVO.endTime}",
            "          </if>",
            "        GROUP BY customer_id",
            "  ) rc ON rc.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, SUM(write_off_amount) AS writeOffAmount, MAX(write_off_time) AS lastBizTime",
            "         FROM erp_receivable_writeoff",
            "        WHERE deleted = 0",
            "          <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR operator_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND operator_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if>",
            "          <if test='reqVO.startTime != null and reqVO.endTime != null'>",
            "          AND write_off_time BETWEEN #{reqVO.startTime} AND #{reqVO.endTime}",
            "          </if>",
            "        GROUP BY customer_id",
            "  ) wo ON wo.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, SUM(receivable_amount) AS otherReceivableAmount, MAX(biz_time) AS lastBizTime",
            "         FROM erp_receivable_other",
            "        WHERE deleted = 0 AND status = 20",
            "          <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR handler_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND handler_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if>",
            "          <if test='reqVO.startTime != null and reqVO.endTime != null'>",
            "          AND biz_time BETWEEN #{reqVO.startTime} AND #{reqVO.endTime}",
            "          </if>",
            "        GROUP BY customer_id",
            "  ) ro ON ro.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, MAX(last_biz_time) AS lastBizTime",
            "         FROM (",
            "               SELECT customer_id, MAX(out_time) AS last_biz_time FROM erp_sale_out WHERE deleted = 0 AND status = 20",
            "               <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR sale_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND sale_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if> GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(return_time) AS last_biz_time FROM erp_sale_return WHERE deleted = 0 AND status = 20",
            "               <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR sale_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND sale_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if> GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(adjust_date) AS last_biz_time FROM erp_sale_price_adjust WHERE deleted = 0 AND status = 20",
            "               <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR adjust_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND adjust_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if> GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(receipt_time) AS last_biz_time FROM erp_finance_receipt WHERE deleted = 0 AND status = 20",
            "               <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR finance_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND finance_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if> GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(write_off_time) AS last_biz_time FROM erp_receivable_writeoff WHERE deleted = 0",
            "               <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR operator_user_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND operator_user_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if> GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(biz_time) AS last_biz_time FROM erp_receivable_other WHERE deleted = 0 AND status = 20",
            "               <if test='!docAll'><choose><when test='docDeptIds != null and docDeptIds.size() > 0'> AND (dept_id IN <foreach collection='docDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach><if test='docSelfUserId != null'> OR handler_id = #{docSelfUserId}</if>)</when><when test='docSelfUserId != null'> AND handler_id = #{docSelfUserId}</when><otherwise> AND 1 = 0</otherwise></choose></if> GROUP BY customer_id",
            "         ) t",
            "        GROUP BY customer_id",
            "  ) lastBiz ON lastBiz.customer_id = c.id",
            " WHERE c.deleted = 0",
            "   <if test='reqVO.showZeroBalance == null or !reqVO.showZeroBalance'>",
            "   AND (IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0)) &lt;&gt; 0",
            "   </if>",
            "   <if test='reqVO.customerId != null'> AND c.id = #{reqVO.customerId} </if>",
            "   <if test='reqVO.customerName != null and reqVO.customerName != \"\"'> AND c.name LIKE CONCAT('%', #{reqVO.customerName}, '%') </if>",
            "   <if test='reqVO.customerType != null'> AND c.customer_type = #{reqVO.customerType} </if>",
            "   <if test='reqVO.saleUserId != null'> AND c.sale_user_id = #{reqVO.saleUserId} </if>",
            "   <if test='reqVO.deptId != null'>",
            "   AND (c.dept_id = #{reqVO.deptId}",
            "        OR (c.allow_multi_dept = true",
            "            AND EXISTS (SELECT 1 FROM erp_customer_dept ecd",
            "                         WHERE ecd.customer_id = c.id",
            "                           AND ecd.deleted = b'0'",
            "                           AND ecd.tenant_id = c.tenant_id",
            "                           AND ecd.dept_id = #{reqVO.deptId})))",
            "   </if>",
            "   <if test='!all'>",
            "   AND (",
            "        <choose>",
            "        <when test='deptIds != null and deptIds.size() > 0'>",
            "        (c.dept_id IN",
            "         <foreach collection='deptIds' item='deptId' open='(' separator=',' close=')'>#{deptId}</foreach>",
            "         OR (c.allow_multi_dept = true",
            "             AND EXISTS (SELECT 1 FROM erp_customer_dept ecd_scope",
            "                          WHERE ecd_scope.customer_id = c.id",
            "                            AND ecd_scope.deleted = b'0'",
            "                            AND ecd_scope.tenant_id = c.tenant_id",
            "                            AND ecd_scope.dept_id IN",
            "                            <foreach collection='deptIds' item='scopeDeptId' open='(' separator=',' close=')'>#{scopeDeptId}</foreach>)))",
            "        </when>",
            "        <otherwise>1 = 0</otherwise>",
            "        </choose>",
            "        <if test='selfUserId != null'> OR c.creator = #{selfUserId} </if>",
            "   )",
            "   </if>",
            "   <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "   AND (c.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "        OR c.contact LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "        OR c.mobile LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "        OR u.nickname LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "        OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "        OR DATE_FORMAT(c.create_time, '%Y-%m-%d %H:%i:%s') LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "   </if>",
            " <choose>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"customerName\"'>ORDER BY customerName ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"customerName\"'>ORDER BY customerName DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"contact\"'>ORDER BY contact ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"contact\"'>ORDER BY contact DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"mobile\"'>ORDER BY mobile ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"mobile\"'>ORDER BY mobile DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"areaId\"'>ORDER BY c.area_id ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"areaId\"'>ORDER BY c.area_id DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"customerType\"'>ORDER BY c.customer_type ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"customerType\"'>ORDER BY c.customer_type DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"deptName\"'>ORDER BY deptName ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"deptName\"'>ORDER BY deptName DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"saleUserName\"'>ORDER BY saleUserName ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"saleUserName\"'>ORDER BY saleUserName DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"routeId\"'>ORDER BY c.route_id ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"routeId\"'>ORDER BY c.route_id DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"baseAmount\"'>ORDER BY baseAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"baseAmount\"'>ORDER BY baseAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"creditLimit\"'>ORDER BY creditLimit ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"creditLimit\"'>ORDER BY creditLimit DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"creditBalance\"'>ORDER BY creditBalance ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"creditBalance\"'>ORDER BY creditBalance DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"creditTermDays\"'>ORDER BY creditTermDays ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"creditTermDays\"'>ORDER BY creditTermDays DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"billType\"'>ORDER BY billType ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"billType\"'>ORDER BY billType DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"receivableAmount\"'>ORDER BY receivableAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"receivableAmount\"'>ORDER BY receivableAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"receivableBalance\"'>ORDER BY receivableBalance ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"receivableBalance\"'>ORDER BY receivableBalance DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"receivedAmount\"'>ORDER BY receivedAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"receivedAmount\"'>ORDER BY receivedAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"unreceivedAmount\"'>ORDER BY unreceivedAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"unreceivedAmount\"'>ORDER BY unreceivedAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"receiveStatus\"'>ORDER BY receiveStatus ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"receiveStatus\"'>ORDER BY receiveStatus DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"saleOutAmount\"'>ORDER BY saleOutAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"saleOutAmount\"'>ORDER BY saleOutAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"saleReturnAmount\"'>ORDER BY saleReturnAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"saleReturnAmount\"'>ORDER BY saleReturnAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"priceAdjustAmount\"'>ORDER BY priceAdjustAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"priceAdjustAmount\"'>ORDER BY priceAdjustAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"receiptAmount\"'>ORDER BY receiptAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"receiptAmount\"'>ORDER BY receiptAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"writeOffAmount\"'>ORDER BY writeOffAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"writeOffAmount\"'>ORDER BY writeOffAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"otherReceivableAmount\"'>ORDER BY otherReceivableAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"otherReceivableAmount\"'>ORDER BY otherReceivableAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"preAdvanceAmount\"'>ORDER BY preAdvanceAmount ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"preAdvanceAmount\"'>ORDER BY preAdvanceAmount DESC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"asc\" and reqVO.orderField == \"lastBizTime\"'>ORDER BY lastBizTime ASC, c.id DESC</when>",
            "   <when test='reqVO.orderDirection == \"desc\" and reqVO.orderField == \"lastBizTime\"'>ORDER BY lastBizTime DESC, c.id DESC</when>",
            "   <otherwise>ORDER BY receivableBalance DESC, c.id DESC</otherwise>",
            " </choose>",
            "</script>"
    })
    List<ErpReceivableAccountDO> selectList(@Param("reqVO") ErpReceivableAccountPageReqVO reqVO,
                                            @Param("deptIds") Collection<Long> deptIds,
                                            @Param("selfUserId") String selfUserId,
                                            @Param("all") boolean all,
                                            @Param("docDeptIds") Collection<Long> docDeptIds,
                                            @Param("docSelfUserId") Long docSelfUserId,
                                            @Param("docAll") boolean docAll);

    default PageResult<ErpReceivableAccountDO> selectPage(ErpReceivableAccountPageReqVO reqVO) {
        return selectPage(reqVO, null, null, true, null, null, true);
    }

    default PageResult<ErpReceivableAccountDO> selectPage(ErpReceivableAccountPageReqVO reqVO,
                                                          Collection<Long> deptIds,
                                                          String selfUserId,
                                                          boolean all, Collection<Long> docDeptIds,
                                                          Long docSelfUserId, boolean docAll) {
        List<ErpReceivableAccountDO> list = selectList(reqVO, deptIds, selfUserId, all,
                docDeptIds, docSelfUserId, docAll);
        long total = list.size();
        int fromIndex = Math.max(0, (reqVO.getPageNo() - 1) * reqVO.getPageSize());
        int toIndex = Math.min(list.size(), fromIndex + reqVO.getPageSize());
        if (fromIndex >= list.size()) {
            return PageResult.empty((long) total);
        }
        return new PageResult<>(list.subList(fromIndex, toIndex), (long) total);
    }

    @Select({
            "<script>",
            "SELECT c.id AS customerId,",
            "       c.name AS customerName,",
            "       c.contact AS contact,",
            "       c.mobile AS mobile,",
            "       c.area_id AS areaId,",
            "       c.customer_type AS customerType,",
            "       c.sale_user_id AS saleUserId,",
            "       u.nickname AS saleUserName,",
            "       c.dept_id AS deptId,",
            "       d.name AS deptName,",
            "       c.route_id AS routeId,",
            "       IFNULL(ext.base_amount, 0) AS baseAmount,",
            "       c.credit_limit AS creditLimit,",
            "       c.credit_term_days AS creditTermDays,",
            "       IFNULL(so.saleOutAmount, 0) AS saleOutAmount,",
            "       IFNULL(sr.saleReturnAmount, 0) AS saleReturnAmount,",
            "       IFNULL(pa.priceAdjustAmount, 0) AS priceAdjustAmount,",
            "       IFNULL(rc.receiptAmount, 0) AS receiptAmount,",
            "       IFNULL(wo.writeOffAmount, 0) AS writeOffAmount,",
            "       IFNULL(ro.otherReceivableAmount, 0) AS otherReceivableAmount,",
            "       IFNULL(ext.advance_amount, 0) AS preAdvanceAmount,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) AS receivableAmount,",
            "       IFNULL(rc.receiptAmount, 0) + IFNULL(wo.writeOffAmount, 0) AS receivedAmount,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) AS unreceivedAmount,",
            "       '应收账款' AS billType,",
            "       CASE WHEN IFNULL(rc.receiptAmount, 0) + IFNULL(wo.writeOffAmount, 0) = 0 THEN '未收款'",
            "            WHEN IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) > 0 THEN '部分收款'",
            "            ELSE '已收款' END AS receiveStatus,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) AS receivableBalance,",
            "       CASE WHEN c.credit_limit IS NULL THEN NULL ELSE c.credit_limit - (IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0)) END AS creditBalance,",
            "       IFNULL(so.saleOutAmount, 0) + IFNULL(pa.priceAdjustAmount, 0) + IFNULL(ro.otherReceivableAmount, 0) - IFNULL(sr.saleReturnAmount, 0) - IFNULL(rc.receiptAmount, 0) - IFNULL(wo.writeOffAmount, 0) + IFNULL(ext.advance_amount, 0) AS totalReceivable,",
            "       lastBiz.lastBizTime AS lastBizTime",
            "  FROM erp_customer c",
            "  LEFT JOIN system_users u ON u.id = c.sale_user_id",
            "  LEFT JOIN system_dept d ON d.id = c.dept_id",
            "  LEFT JOIN erp_customer_extend_info ext ON ext.customer_id = c.id",
            "  LEFT JOIN (SELECT customer_id, SUM(total_price) AS saleOutAmount, MAX(out_time) AS lastBizTime FROM erp_sale_out WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id) so ON so.customer_id = c.id",
            "  LEFT JOIN (SELECT customer_id, SUM(total_price) AS saleReturnAmount FROM erp_sale_return WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id) sr ON sr.customer_id = c.id",
            "  LEFT JOIN (SELECT customer_id, SUM(total_adjust_price) AS priceAdjustAmount FROM erp_sale_price_adjust WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id) pa ON pa.customer_id = c.id",
            "  LEFT JOIN (SELECT customer_id, SUM(total_price) AS receiptAmount FROM erp_finance_receipt WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id) rc ON rc.customer_id = c.id",
            "  LEFT JOIN (SELECT customer_id, SUM(write_off_amount) AS writeOffAmount FROM erp_receivable_writeoff WHERE deleted = 0 AND customer_id = #{customerId} GROUP BY customer_id) wo ON wo.customer_id = c.id",
            "  LEFT JOIN (SELECT customer_id, SUM(receivable_amount) AS otherReceivableAmount FROM erp_receivable_other WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id) ro ON ro.customer_id = c.id",
            "  LEFT JOIN (",
            "       SELECT customer_id, MAX(last_biz_time) AS lastBizTime",
            "         FROM (",
            "               SELECT customer_id, MAX(out_time) AS last_biz_time FROM erp_sale_out WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(return_time) AS last_biz_time FROM erp_sale_return WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(adjust_date) AS last_biz_time FROM erp_sale_price_adjust WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(receipt_time) AS last_biz_time FROM erp_finance_receipt WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(write_off_time) AS last_biz_time FROM erp_receivable_writeoff WHERE deleted = 0 AND customer_id = #{customerId} GROUP BY customer_id",
            "               UNION ALL",
            "               SELECT customer_id, MAX(biz_time) AS last_biz_time FROM erp_receivable_other WHERE deleted = 0 AND status = 20 AND customer_id = #{customerId} GROUP BY customer_id",
            "         ) t",
            "        GROUP BY customer_id",
            "  ) lastBiz ON lastBiz.customer_id = c.id",
            " WHERE c.deleted = 0 AND c.id = #{customerId}",
            "</script>"
    })
    ErpReceivableAccountDO selectByCustomerId(@Param("customerId") Long customerId);

}
