#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jul 21 13:50:08 CST 2026
maven-metadata-huaweicloud.xml.lastUpdated=1784613008050
maven-metadata-alimaven.xml.lastUpdated=1784613008055
maven-metadata-spring-snapshots.xml.error=
maven-metadata-spring-milestones.xml.lastUpdated=1784613008053
maven-metadata-spring-snapshots.xml.lastUpdated=1784613008053
maven-metadata-spring-milestones.xml.error=
maven-metadata-aliyunmaven.xml.lastUpdated=1784613008052
