#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 28 11:33:54 CST 2026
maven-metadata-alimaven.xml.lastUpdated=1779939234561
maven-metadata-huaweicloud.xml.lastUpdated=1779939234558
maven-metadata-spring-milestones.xml.lastUpdated=1779939234560
maven-metadata-spring-snapshots.xml.error=
maven-metadata-spring-milestones.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1779939234560
maven-metadata-aliyunmaven.xml.lastUpdated=1779939234559
