#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jul 21 13:53:47 CST 2026
maven-metadata-aliyunmaven.xml.error=
maven-metadata-huaweicloud.xml.lastUpdated=1784613227738
maven-metadata-spring-snapshots.xml.error=
maven-metadata-huaweicloud.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1784613227742
maven-metadata-aliyunmaven.xml.lastUpdated=1784613227742
