package cn.iocoder.yudao.module.erp.dal.mysql.report;

import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.yudao.module.erp.controller.admin.report.vo.purchase.ErpPurchaseReportDetailRespVO;
import cn.iocoder.yudao.module.erp.controller.admin.report.vo.purchase.ErpPurchaseReportPageReqVO;
import cn.iocoder.yudao.module.erp.controller.admin.report.vo.purchase.ErpPurchaseReportProductRespVO;
import cn.iocoder.yudao.module.erp.dal.dataobject.purchase.ErpPurchaseInDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.Collection;
import java.util.List;

@Mapper
public interface ErpPurchaseReportMapper extends BaseMapperX<ErpPurchaseInDO> {

    @Select({
            "<script>",
            "SELECT * FROM (",
            "  SELECT CONCAT('in-', pi.id) AS rowKey,",
            "         s.id AS supplierId, s.name AS supplierName, s.contact AS contact, s.mobile AS mobile,",
            "         COALESCE(pi.dept_id, s.dept_id) AS deptId, d.name AS deptName,",
            "         pi.purchaser AS purchaser, u.nickname AS purchaserName,",
            "         '采购入库' AS docType, 1 AS bizType, pi.id AS bizId, pi.in_time AS docDate, pi.no AS docNo,",
            "         IFNULL(pi.total_count, 0) AS bizCount,",
            "         IFNULL(pi.total_count, 0) AS purchaseCount, IFNULL(pi.total_price, 0) AS purchaseAmount,",
            "         0 AS returnCount, 0 AS returnAmount, IFNULL(pi.total_price, 0) AS netAmount",
            "    FROM erp_purchase_in pi",
            "    INNER JOIN erp_supplier s ON s.id = pi.supplier_id AND s.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(pi.dept_id, s.dept_id)",
            "    LEFT JOIN system_users u ON u.id = pi.purchaser AND u.deleted = b'0'",
            "   WHERE pi.deleted = 0 AND pi.status = 20",
            "     <if test='reqVO.supplierId != null'> AND pi.supplier_id = #{reqVO.supplierId} </if>",
            "     <if test='reqVO.purchaser != null and reqVO.purchaser != \"\"'> AND pi.purchaser = #{reqVO.purchaser} </if>",
            "     <if test='reqVO.startTime != null'> AND pi.in_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND pi.in_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (pi.dept_id = #{reqVO.deptId} OR s.dept_id = #{reqVO.deptId}",
            "         OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd",
            "              WHERE esd.supplier_id = s.id AND esd.deleted = b'0' AND esd.tenant_id = s.tenant_id",
            "                AND esd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             pi.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR pi.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>pi.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (s.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd_scope",
            "                   WHERE esd_scope.supplier_id = s.id AND esd_scope.deleted = b'0'",
            "                     AND esd_scope.tenant_id = s.tenant_id AND esd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR s.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>s.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (pi.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR s.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR s.contact LIKE CONCAT('%', #{reqVO.keyword}, '%') OR s.mobile LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR u.nickname LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            "  UNION ALL",
            "  SELECT CONCAT('return-', pr.id) AS rowKey,",
            "         s.id AS supplierId, s.name AS supplierName, s.contact AS contact, s.mobile AS mobile,",
            "         COALESCE(pr.dept_id, s.dept_id) AS deptId, d.name AS deptName,",
            "         pr.purchaser AS purchaser, u.nickname AS purchaserName,",
            "         '采购退货' AS docType, 2 AS bizType, pr.id AS bizId, pr.return_time AS docDate, pr.no AS docNo,",
            "         IFNULL(pr.total_count, 0) AS bizCount,",
            "         0 AS purchaseCount, 0 AS purchaseAmount,",
            "         IFNULL(pr.total_count, 0) AS returnCount, IFNULL(pr.total_price, 0) AS returnAmount,",
            "         -IFNULL(pr.total_price, 0) AS netAmount",
            "    FROM erp_purchase_return pr",
            "    INNER JOIN erp_supplier s ON s.id = pr.supplier_id AND s.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(pr.dept_id, s.dept_id)",
            "    LEFT JOIN system_users u ON u.id = pr.purchaser AND u.deleted = b'0'",
            "   WHERE pr.deleted = 0 AND pr.status = 20",
            "     <if test='reqVO.supplierId != null'> AND pr.supplier_id = #{reqVO.supplierId} </if>",
            "     <if test='reqVO.purchaser != null and reqVO.purchaser != \"\"'> AND pr.purchaser = #{reqVO.purchaser} </if>",
            "     <if test='reqVO.startTime != null'> AND pr.return_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND pr.return_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (pr.dept_id = #{reqVO.deptId} OR s.dept_id = #{reqVO.deptId}",
            "         OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd",
            "              WHERE esd.supplier_id = s.id AND esd.deleted = b'0' AND esd.tenant_id = s.tenant_id",
            "                AND esd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             pr.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR pr.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>pr.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (s.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd_scope",
            "                   WHERE esd_scope.supplier_id = s.id AND esd_scope.deleted = b'0'",
            "                     AND esd_scope.tenant_id = s.tenant_id AND esd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR s.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>s.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (pr.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR s.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR s.contact LIKE CONCAT('%', #{reqVO.keyword}, '%') OR s.mobile LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR u.nickname LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            ") t ORDER BY t.docDate ASC, t.docNo ASC, t.bizId ASC",
            "</script>"
    })
    List<ErpPurchaseReportDetailRespVO> selectRows(@Param("reqVO") ErpPurchaseReportPageReqVO reqVO,
                                                   @Param("partyDeptIds") Collection<Long> partyDeptIds,
                                                   @Param("partySelfUserId") String partySelfUserId,
                                                   @Param("partyAll") boolean partyAll,
                                                   @Param("documentDeptIds") Collection<Long> documentDeptIds,
                                                   @Param("documentSelfUserId") String documentSelfUserId,
                                                   @Param("documentAll") boolean documentAll);

    @Select({
            "<script>",
            "SELECT t.productId,",
            "       MAX(t.productCode) AS productCode,",
            "       MAX(t.productName) AS productName,",
            "       MAX(t.barCode) AS barCode,",
            "       MAX(t.unitName) AS unitName,",
            "       MAX(t.brand) AS brand,",
            "       MAX(t.standard) AS standard,",
            "       MAX(t.vehicleModel) AS vehicleModel,",
            "       MAX(t.drawingNo) AS drawingNo,",
            "       COUNT(DISTINCT t.supplierId) AS supplierCount,",
            "       COUNT(DISTINCT t.docKey) AS docCount,",
            "       SUM(t.purchaseCount) AS purchaseCount,",
            "       SUM(t.purchaseAmount) AS purchaseAmount,",
            "       SUM(t.returnCount) AS returnCount,",
            "       SUM(t.returnAmount) AS returnAmount,",
            "       SUM(t.netAmount) AS netAmount,",
            "       MAX(t.docDate) AS lastBizTime",
            "  FROM (",
            "  SELECT pii.product_id AS productId,",
            "         p.code AS productCode, p.name AS productName, COALESCE(pii.bar_code, p.bar_code) AS barCode,",
            "         pu.name AS unitName, COALESCE(pii.brand, p.brand) AS brand, p.standard AS standard,",
            "         COALESCE(pii.vehicle_model, p.vehicle_model) AS vehicleModel, COALESCE(pii.drawing_no, p.drawing_no) AS drawingNo,",
            "         pi.supplier_id AS supplierId, CONCAT('in-', pi.id) AS docKey, pi.in_time AS docDate,",
            "         IFNULL(pii.count, 0) AS purchaseCount, IFNULL(pii.total_price, 0) AS purchaseAmount,",
            "         0 AS returnCount, 0 AS returnAmount, IFNULL(pii.total_price, 0) AS netAmount",
            "    FROM erp_purchase_in_items pii",
            "    INNER JOIN erp_purchase_in pi ON pi.id = pii.in_id AND pi.deleted = 0 AND pi.status = 20",
            "    INNER JOIN erp_supplier s ON s.id = pi.supplier_id AND s.deleted = 0",
            "    LEFT JOIN erp_product p ON p.id = pii.product_id AND p.deleted = 0",
            "    LEFT JOIN erp_product_unit pu ON pu.id = pii.product_unit_id AND pu.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(pi.dept_id, s.dept_id)",
            "   WHERE pii.deleted = 0 AND pii.product_id IS NOT NULL",
            "     <if test='reqVO.supplierId != null'> AND pi.supplier_id = #{reqVO.supplierId} </if>",
            "     <if test='reqVO.purchaser != null and reqVO.purchaser != \"\"'> AND pi.purchaser = #{reqVO.purchaser} </if>",
            "     <if test='reqVO.startTime != null'> AND pi.in_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND pi.in_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (pi.dept_id = #{reqVO.deptId} OR s.dept_id = #{reqVO.deptId}",
            "         OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd",
            "              WHERE esd.supplier_id = s.id AND esd.deleted = b'0' AND esd.tenant_id = s.tenant_id",
            "                AND esd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             pi.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR pi.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>pi.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (s.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd_scope",
            "                   WHERE esd_scope.supplier_id = s.id AND esd_scope.deleted = b'0'",
            "                     AND esd_scope.tenant_id = s.tenant_id AND esd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR s.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>s.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (pi.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR s.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.code LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.bar_code LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.standard LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.brand LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.vehicle_model LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.drawing_no LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR pii.bar_code LIKE CONCAT('%', #{reqVO.keyword}, '%') OR pii.brand LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR pii.vehicle_model LIKE CONCAT('%', #{reqVO.keyword}, '%') OR pii.drawing_no LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            "  UNION ALL",
            "  SELECT pri.product_id AS productId,",
            "         p.code AS productCode, p.name AS productName, COALESCE(pri.bar_code, p.bar_code) AS barCode,",
            "         pu.name AS unitName, COALESCE(pri.brand, p.brand) AS brand, p.standard AS standard,",
            "         COALESCE(pri.vehicle_model, p.vehicle_model) AS vehicleModel, COALESCE(pri.drawing_no, p.drawing_no) AS drawingNo,",
            "         pr.supplier_id AS supplierId, CONCAT('return-', pr.id) AS docKey, pr.return_time AS docDate,",
            "         0 AS purchaseCount, 0 AS purchaseAmount,",
            "         IFNULL(pri.count, 0) AS returnCount, IFNULL(pri.total_price, 0) AS returnAmount,",
            "         -IFNULL(pri.total_price, 0) AS netAmount",
            "    FROM erp_purchase_return_items pri",
            "    INNER JOIN erp_purchase_return pr ON pr.id = pri.return_id AND pr.deleted = 0 AND pr.status = 20",
            "    INNER JOIN erp_supplier s ON s.id = pr.supplier_id AND s.deleted = 0",
            "    LEFT JOIN erp_product p ON p.id = pri.product_id AND p.deleted = 0",
            "    LEFT JOIN erp_product_unit pu ON pu.id = pri.product_unit_id AND pu.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(pr.dept_id, s.dept_id)",
            "   WHERE pri.deleted = 0 AND pri.product_id IS NOT NULL",
            "     <if test='reqVO.supplierId != null'> AND pr.supplier_id = #{reqVO.supplierId} </if>",
            "     <if test='reqVO.purchaser != null and reqVO.purchaser != \"\"'> AND pr.purchaser = #{reqVO.purchaser} </if>",
            "     <if test='reqVO.startTime != null'> AND pr.return_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND pr.return_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (pr.dept_id = #{reqVO.deptId} OR s.dept_id = #{reqVO.deptId}",
            "         OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd",
            "              WHERE esd.supplier_id = s.id AND esd.deleted = b'0' AND esd.tenant_id = s.tenant_id",
            "                AND esd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             pr.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR pr.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>pr.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (s.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (s.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_supplier_dept esd_scope",
            "                   WHERE esd_scope.supplier_id = s.id AND esd_scope.deleted = b'0'",
            "                     AND esd_scope.tenant_id = s.tenant_id AND esd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR s.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>s.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (pr.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR s.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.code LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.bar_code LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.standard LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.brand LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.vehicle_model LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.drawing_no LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR pri.bar_code LIKE CONCAT('%', #{reqVO.keyword}, '%') OR pri.brand LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR pri.vehicle_model LIKE CONCAT('%', #{reqVO.keyword}, '%') OR pri.drawing_no LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            ") t GROUP BY t.productId",
            "</script>"
    })
    List<ErpPurchaseReportProductRespVO> selectProductRows(@Param("reqVO") ErpPurchaseReportPageReqVO reqVO,
                                                           @Param("partyDeptIds") Collection<Long> partyDeptIds,
                                                           @Param("partySelfUserId") String partySelfUserId,
                                                           @Param("partyAll") boolean partyAll,
                                                           @Param("documentDeptIds") Collection<Long> documentDeptIds,
                                                           @Param("documentSelfUserId") String documentSelfUserId,
                                                           @Param("documentAll") boolean documentAll);
}
