package cn.iocoder.yudao.module.erp.dal.mysql.report;

import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.yudao.module.erp.controller.admin.report.vo.sale.ErpSaleReportDetailRespVO;
import cn.iocoder.yudao.module.erp.controller.admin.report.vo.sale.ErpSaleReportPageReqVO;
import cn.iocoder.yudao.module.erp.controller.admin.report.vo.sale.ErpSaleReportProductRespVO;
import cn.iocoder.yudao.module.erp.dal.dataobject.sale.ErpSaleOutDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.Collection;
import java.util.List;

@Mapper
public interface ErpSaleReportMapper extends BaseMapperX<ErpSaleOutDO> {

    @Select({
            "<script>",
            "SELECT * FROM (",
            "  SELECT CONCAT('out-', so.id) AS rowKey,",
            "         c.id AS customerId, c.name AS customerName, c.contact AS contact, c.mobile AS mobile,",
            "         COALESCE(so.dept_id, c.dept_id) AS deptId, d.name AS deptName,",
            "         so.sale_user_id AS saleUserId, u.nickname AS saleUserName,",
            "         '销售出库' AS docType, 1 AS bizType, so.id AS bizId, so.out_time AS docDate, so.no AS docNo,",
            "         IFNULL(so.total_count, 0) AS bizCount,",
            "         IFNULL(so.total_count, 0) AS saleCount, IFNULL(so.total_price, 0) AS saleAmount,",
            "         0 AS returnCount, 0 AS returnAmount, IFNULL(so.total_price, 0) AS netAmount",
            "    FROM erp_sale_out so",
            "    INNER JOIN erp_customer c ON c.id = so.customer_id AND c.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(so.dept_id, c.dept_id)",
            "    LEFT JOIN system_users u ON u.id = so.sale_user_id",
            "   WHERE so.deleted = 0 AND so.status = 20",
            "     <if test='reqVO.customerId != null'> AND so.customer_id = #{reqVO.customerId} </if>",
            "     <if test='reqVO.saleUserId != null'> AND so.sale_user_id = #{reqVO.saleUserId} </if>",
            "     <if test='reqVO.startTime != null'> AND so.out_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND so.out_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (so.dept_id = #{reqVO.deptId} OR c.dept_id = #{reqVO.deptId}",
            "         OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd",
            "              WHERE ecd.customer_id = c.id AND ecd.deleted = b'0' AND ecd.tenant_id = c.tenant_id",
            "                AND ecd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             so.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR so.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>so.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (c.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd_scope",
            "                   WHERE ecd_scope.customer_id = c.id AND ecd_scope.deleted = b'0'",
            "                     AND ecd_scope.tenant_id = c.tenant_id AND ecd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR c.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>c.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (so.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR c.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR c.contact LIKE CONCAT('%', #{reqVO.keyword}, '%') OR c.mobile LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR u.nickname LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            "  UNION ALL",
            "  SELECT CONCAT('return-', sr.id) AS rowKey,",
            "         c.id AS customerId, c.name AS customerName, c.contact AS contact, c.mobile AS mobile,",
            "         COALESCE(sr.dept_id, c.dept_id) AS deptId, d.name AS deptName,",
            "         sr.sale_user_id AS saleUserId, u.nickname AS saleUserName,",
            "         '销售退货' AS docType, 2 AS bizType, sr.id AS bizId, sr.return_time AS docDate, sr.no AS docNo,",
            "         IFNULL(sr.total_count, 0) AS bizCount,",
            "         0 AS saleCount, 0 AS saleAmount,",
            "         IFNULL(sr.total_count, 0) AS returnCount, IFNULL(sr.total_price, 0) AS returnAmount,",
            "         -IFNULL(sr.total_price, 0) AS netAmount",
            "    FROM erp_sale_return sr",
            "    INNER JOIN erp_customer c ON c.id = sr.customer_id AND c.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(sr.dept_id, c.dept_id)",
            "    LEFT JOIN system_users u ON u.id = sr.sale_user_id",
            "   WHERE sr.deleted = 0 AND sr.status = 20",
            "     <if test='reqVO.customerId != null'> AND sr.customer_id = #{reqVO.customerId} </if>",
            "     <if test='reqVO.saleUserId != null'> AND sr.sale_user_id = #{reqVO.saleUserId} </if>",
            "     <if test='reqVO.startTime != null'> AND sr.return_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND sr.return_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (sr.dept_id = #{reqVO.deptId} OR c.dept_id = #{reqVO.deptId}",
            "         OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd",
            "              WHERE ecd.customer_id = c.id AND ecd.deleted = b'0' AND ecd.tenant_id = c.tenant_id",
            "                AND ecd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             sr.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR sr.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>sr.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (c.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd_scope",
            "                   WHERE ecd_scope.customer_id = c.id AND ecd_scope.deleted = b'0'",
            "                     AND ecd_scope.tenant_id = c.tenant_id AND ecd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR c.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>c.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (sr.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR c.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR c.contact LIKE CONCAT('%', #{reqVO.keyword}, '%') OR c.mobile LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR u.nickname LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            ") t ORDER BY t.docDate ASC, t.docNo ASC, t.bizId ASC",
            "</script>"
    })
    List<ErpSaleReportDetailRespVO> selectRows(@Param("reqVO") ErpSaleReportPageReqVO reqVO,
                                               @Param("partyDeptIds") Collection<Long> partyDeptIds,
                                               @Param("partySelfUserId") String partySelfUserId,
                                               @Param("partyAll") boolean partyAll,
                                               @Param("documentDeptIds") Collection<Long> documentDeptIds,
                                               @Param("documentSelfUserId") String documentSelfUserId,
                                               @Param("documentAll") boolean documentAll);

    @Select({
            "<script>",
            "SELECT t.productId,",
            "       MAX(t.productCode) AS productCode,",
            "       MAX(t.productName) AS productName,",
            "       MAX(t.barCode) AS barCode,",
            "       MAX(t.unitName) AS unitName,",
            "       MAX(t.brand) AS brand,",
            "       MAX(t.standard) AS standard,",
            "       MAX(t.vehicleModel) AS vehicleModel,",
            "       MAX(t.drawingNo) AS drawingNo,",
            "       COUNT(DISTINCT t.customerId) AS customerCount,",
            "       COUNT(DISTINCT t.docKey) AS docCount,",
            "       SUM(t.saleCount) AS saleCount,",
            "       SUM(t.saleAmount) AS saleAmount,",
            "       SUM(t.returnCount) AS returnCount,",
            "       SUM(t.returnAmount) AS returnAmount,",
            "       SUM(t.netAmount) AS netAmount,",
            "       MAX(t.docDate) AS lastBizTime",
            "  FROM (",
            "  SELECT soi.product_id AS productId,",
            "         p.code AS productCode, p.name AS productName, p.bar_code AS barCode,",
            "         pu.name AS unitName, COALESCE(soi.brand, p.brand) AS brand, COALESCE(soi.standard, p.standard) AS standard,",
            "         COALESCE(soi.vehicle_model, p.vehicle_model) AS vehicleModel, COALESCE(soi.drawing_no, p.drawing_no) AS drawingNo,",
            "         so.customer_id AS customerId, CONCAT('out-', so.id) AS docKey, so.out_time AS docDate,",
            "         IFNULL(soi.count, 0) AS saleCount, IFNULL(soi.total_price, 0) AS saleAmount,",
            "         0 AS returnCount, 0 AS returnAmount, IFNULL(soi.total_price, 0) AS netAmount",
            "    FROM erp_sale_out_items soi",
            "    INNER JOIN erp_sale_out so ON so.id = soi.out_id AND so.deleted = 0 AND so.status = 20",
            "    INNER JOIN erp_customer c ON c.id = so.customer_id AND c.deleted = 0",
            "    LEFT JOIN erp_product p ON p.id = soi.product_id AND p.deleted = 0",
            "    LEFT JOIN erp_product_unit pu ON pu.id = soi.product_unit_id AND pu.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(so.dept_id, c.dept_id)",
            "    LEFT JOIN system_users u ON u.id = so.sale_user_id",
            "   WHERE soi.deleted = 0 AND soi.product_id IS NOT NULL",
            "     <if test='reqVO.customerId != null'> AND so.customer_id = #{reqVO.customerId} </if>",
            "     <if test='reqVO.saleUserId != null'> AND so.sale_user_id = #{reqVO.saleUserId} </if>",
            "     <if test='reqVO.startTime != null'> AND so.out_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND so.out_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (so.dept_id = #{reqVO.deptId} OR c.dept_id = #{reqVO.deptId}",
            "         OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd",
            "              WHERE ecd.customer_id = c.id AND ecd.deleted = b'0' AND ecd.tenant_id = c.tenant_id",
            "                AND ecd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             so.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR so.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>so.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (c.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd_scope",
            "                   WHERE ecd_scope.customer_id = c.id AND ecd_scope.deleted = b'0'",
            "                     AND ecd_scope.tenant_id = c.tenant_id AND ecd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR c.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>c.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (so.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR c.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR u.nickname LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.code LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.bar_code LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.standard LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.brand LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.vehicle_model LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.drawing_no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR soi.brand LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR soi.vehicle_model LIKE CONCAT('%', #{reqVO.keyword}, '%') OR soi.drawing_no LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            "  UNION ALL",
            "  SELECT sri.product_id AS productId,",
            "         p.code AS productCode, p.name AS productName, p.bar_code AS barCode,",
            "         pu.name AS unitName, p.brand AS brand, p.standard AS standard,",
            "         p.vehicle_model AS vehicleModel, p.drawing_no AS drawingNo,",
            "         sr.customer_id AS customerId, CONCAT('return-', sr.id) AS docKey, sr.return_time AS docDate,",
            "         0 AS saleCount, 0 AS saleAmount,",
            "         IFNULL(sri.count, 0) AS returnCount, IFNULL(sri.total_price, 0) AS returnAmount,",
            "         -IFNULL(sri.total_price, 0) AS netAmount",
            "    FROM erp_sale_return_items sri",
            "    INNER JOIN erp_sale_return sr ON sr.id = sri.return_id AND sr.deleted = 0 AND sr.status = 20",
            "    INNER JOIN erp_customer c ON c.id = sr.customer_id AND c.deleted = 0",
            "    LEFT JOIN erp_product p ON p.id = sri.product_id AND p.deleted = 0",
            "    LEFT JOIN erp_product_unit pu ON pu.id = sri.product_unit_id AND pu.deleted = 0",
            "    LEFT JOIN system_dept d ON d.id = COALESCE(sr.dept_id, c.dept_id)",
            "    LEFT JOIN system_users u ON u.id = sr.sale_user_id",
            "   WHERE sri.deleted = 0 AND sri.product_id IS NOT NULL",
            "     <if test='reqVO.customerId != null'> AND sr.customer_id = #{reqVO.customerId} </if>",
            "     <if test='reqVO.saleUserId != null'> AND sr.sale_user_id = #{reqVO.saleUserId} </if>",
            "     <if test='reqVO.startTime != null'> AND sr.return_time &gt;= #{reqVO.startTime} </if>",
            "     <if test='reqVO.endTime != null'> AND sr.return_time &lt;= #{reqVO.endTime} </if>",
            "     <if test='reqVO.deptId != null'>",
            "       AND (sr.dept_id = #{reqVO.deptId} OR c.dept_id = #{reqVO.deptId}",
            "         OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd",
            "              WHERE ecd.customer_id = c.id AND ecd.deleted = b'0' AND ecd.tenant_id = c.tenant_id",
            "                AND ecd.dept_id = #{reqVO.deptId})))",
            "     </if>",
            "     <if test='!documentAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='documentDeptIds != null and documentDeptIds.size() &gt; 0'>",
            "             sr.dept_id IN <foreach collection='documentDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "             <if test='documentSelfUserId != null'> OR sr.creator = #{documentSelfUserId}</if>",
            "           </when>",
            "           <when test='documentSelfUserId != null'>sr.creator = #{documentSelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='!partyAll'>",
            "       AND (",
            "         <choose>",
            "           <when test='partyDeptIds != null and partyDeptIds.size() &gt; 0'>",
            "             (c.dept_id IN <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>",
            "              OR (c.allow_multi_dept = true AND EXISTS (SELECT 1 FROM erp_customer_dept ecd_scope",
            "                   WHERE ecd_scope.customer_id = c.id AND ecd_scope.deleted = b'0'",
            "                     AND ecd_scope.tenant_id = c.tenant_id AND ecd_scope.dept_id IN",
            "                     <foreach collection='partyDeptIds' item='id' open='(' separator=',' close=')'>#{id}</foreach>)))",
            "             <if test='partySelfUserId != null'> OR c.creator = #{partySelfUserId}</if>",
            "           </when>",
            "           <when test='partySelfUserId != null'>c.creator = #{partySelfUserId}</when>",
            "           <otherwise>1 = 0</otherwise>",
            "         </choose>",
            "       )",
            "     </if>",
            "     <if test='reqVO.keyword != null and reqVO.keyword != \"\"'>",
            "       AND (sr.no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR c.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR d.name LIKE CONCAT('%', #{reqVO.keyword}, '%') OR u.nickname LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.code LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.name LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.bar_code LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.standard LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.brand LIKE CONCAT('%', #{reqVO.keyword}, '%') OR p.vehicle_model LIKE CONCAT('%', #{reqVO.keyword}, '%')",
            "         OR p.drawing_no LIKE CONCAT('%', #{reqVO.keyword}, '%') OR sri.return_reason LIKE CONCAT('%', #{reqVO.keyword}, '%'))",
            "     </if>",
            ") t GROUP BY t.productId",
            "</script>"
    })
    List<ErpSaleReportProductRespVO> selectProductRows(@Param("reqVO") ErpSaleReportPageReqVO reqVO,
                                                       @Param("partyDeptIds") Collection<Long> partyDeptIds,
                                                       @Param("partySelfUserId") String partySelfUserId,
                                                       @Param("partyAll") boolean partyAll,
                                                       @Param("documentDeptIds") Collection<Long> documentDeptIds,
                                                       @Param("documentSelfUserId") String documentSelfUserId,
                                                       @Param("documentAll") boolean documentAll);
}
