#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jul 21 13:50:02 CST 2026
maven-metadata-apache.snapshots.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1784613002835
maven-metadata-aliyunmaven.xml.lastUpdated=1784613002834
maven-metadata-spring-milestones.xml.error=
maven-metadata-spring-milestones.xml.lastUpdated=1784613002835
maven-metadata-spring-snapshots.xml.error=
maven-metadata-alimaven.xml.lastUpdated=1784613002835
maven-metadata-huaweicloud.xml.lastUpdated=1784613002829
maven-metadata-apache.snapshots.xml.lastUpdated=1784613002835
