#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 28 11:27:12 CST 2026
maven-metadata-apache.snapshots.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1779938832662
maven-metadata-aliyunmaven.xml.lastUpdated=1779938832661
maven-metadata-spring-milestones.xml.error=
maven-metadata-spring-milestones.xml.lastUpdated=1779938832662
maven-metadata-spring-snapshots.xml.error=
maven-metadata-alimaven.xml.lastUpdated=1779938832663
maven-metadata-huaweicloud.xml.lastUpdated=1779938832660
maven-metadata-apache.snapshots.xml.lastUpdated=1779938832663
