#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jul 21 13:50:04 CST 2026
maven-metadata-apache.snapshots.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1784613004144
maven-metadata-aliyunmaven.xml.lastUpdated=1784613004140
maven-metadata-spring-milestones.xml.error=
maven-metadata-spring-milestones.xml.lastUpdated=1784613004142
maven-metadata-spring-snapshots.xml.error=
maven-metadata-alimaven.xml.lastUpdated=1784613004144
maven-metadata-huaweicloud.xml.lastUpdated=1784613004140
maven-metadata-apache.snapshots.xml.lastUpdated=1784613004144
