-- ERP sale price adjust v12: redo sale bill without duplicated stock deduction.
-- Execute after erp_sale_return_v11.sql.

ALTER TABLE `erp_sale_out`
    ADD COLUMN `adjusted` bit(1) DEFAULT b'0' COMMENT 'Whether voided by sale price adjustment' AFTER `remark`,
    ADD COLUMN `adjust_source_out_id` bigint DEFAULT NULL COMMENT 'Original sale out id for price adjustment' AFTER `adjusted`,
    ADD COLUMN `adjust_new_out_id` bigint DEFAULT NULL COMMENT 'New sale out id generated by price adjustment' AFTER `adjust_source_out_id`,
    ADD COLUMN `adjust_price_adjust_id` bigint DEFAULT NULL COMMENT 'Sale price adjust id' AFTER `adjust_new_out_id`;

ALTER TABLE `erp_sale_out`
    ADD INDEX `idx_sale_out_adjust_source_out_id` (`adjust_source_out_id`),
    ADD INDEX `idx_sale_out_adjust_new_out_id` (`adjust_new_out_id`),
    ADD INDEX `idx_sale_out_adjust_price_adjust_id` (`adjust_price_adjust_id`);

ALTER TABLE `erp_sale_price_adjust`
    ADD COLUMN `original_sale_out_id` bigint DEFAULT NULL COMMENT 'Original sale out id' AFTER `total_adjust_price`,
    ADD COLUMN `original_sale_out_no` varchar(64) DEFAULT NULL COMMENT 'Original sale out no' AFTER `original_sale_out_id`,
    ADD COLUMN `new_sale_out_id` bigint DEFAULT NULL COMMENT 'New sale out id' AFTER `original_sale_out_no`,
    ADD COLUMN `new_sale_out_no` varchar(64) DEFAULT NULL COMMENT 'New sale out no' AFTER `new_sale_out_id`,
    ADD COLUMN `adjust_reason` varchar(500) DEFAULT NULL COMMENT 'Sale price adjust reason' AFTER `new_sale_out_no`;
