-- ERP 供应商基础表（v20）
-- 对齐《供应商基础表-修改版.md》Tab 2 ~ Tab 9

CREATE TABLE IF NOT EXISTS `erp_supplier_contact` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `name` varchar(64) NOT NULL COMMENT '姓名',
    `salesperson` bit(1) DEFAULT b'0' COMMENT '导购员',
    `telephone` varchar(32) DEFAULT NULL COMMENT '联系电话',
    `mobile` varchar(32) NOT NULL COMMENT '移动电话',
    `address` varchar(255) DEFAULT NULL COMMENT '联系地址',
    `email` varchar(128) DEFAULT NULL COMMENT '电子邮箱',
    `gender` tinyint DEFAULT NULL COMMENT '性别 1=男 2=女',
    `position` varchar(64) DEFAULT NULL COMMENT '职务',
    `company_id` bigint NOT NULL COMMENT '所属公司（供应商ID，自关联）',
    `fax` varchar(32) DEFAULT NULL COMMENT '传真',
    `dept_id` bigint DEFAULT NULL COMMENT '部门编号',
    `importance` tinyint DEFAULT 1 COMMENT '重要性 1=普通 2=重要 3=决策人',
    `commission_rate` decimal(10,2) DEFAULT NULL COMMENT '提成率（百分比）',
    `fixed_commission` bit(1) DEFAULT b'0' COMMENT '固定提成',
    `post_code` varchar(20) DEFAULT NULL COMMENT '邮编',
    `qq` varchar(32) DEFAULT NULL COMMENT 'QQ号',
    `birthday` date DEFAULT NULL COMMENT '生日',
    `primary_contact` bit(1) DEFAULT b'0' COMMENT '主要联系人',
    `receiver_contact` bit(1) DEFAULT b'0' COMMENT '收货主要联系人',
    `settle_contact` bit(1) DEFAULT b'0' COMMENT '结算主要联系人',
    `message_contact` bit(1) DEFAULT b'0' COMMENT '消息主要联系人',
    `wechat` varchar(64) DEFAULT NULL COMMENT '微信',
    `wechat_official_status` tinyint DEFAULT 0 COMMENT '关注公众号状态 0未关注 1已邀请 2已关注',
    `order_access` bit(1) DEFAULT b'0' COMMENT '订单访问权限',
    `ecommerce_access` bit(1) DEFAULT b'0' COMMENT '电商访问',
    `business_card_front_url` varchar(512) DEFAULT NULL COMMENT '名片正面',
    `business_card_back_url` varchar(512) DEFAULT NULL COMMENT '名片背面',
    `last_contact_time` datetime DEFAULT NULL COMMENT '最后一次联系时间',
    `status` tinyint DEFAULT 0 COMMENT '状态',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_supplier_contact_supplier_id` (`supplier_id`),
    KEY `idx_supplier_contact_mobile` (`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商联系人';

CREATE TABLE IF NOT EXISTS `erp_supplier_contract` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `contract_no` varchar(64) NOT NULL COMMENT '合同编号',
    `contract_date` datetime NOT NULL COMMENT '合同日期',
    `contract_type` varchar(64) DEFAULT NULL COMMENT '合同类型',
    `settle_method` varchar(64) DEFAULT NULL COMMENT '结算方式',
    `start_time` datetime DEFAULT NULL COMMENT '生效日期',
    `transport_method` varchar(64) DEFAULT NULL COMMENT '运输方式',
    `end_time` datetime DEFAULT NULL COMMENT '终止日期',
    `main_contract` bit(1) DEFAULT b'0' COMMENT '主要合同',
    `rebate_enabled` bit(1) DEFAULT b'0' COMMENT '返点证集',
    `freight_settle_method` tinyint DEFAULT NULL COMMENT '运费结算方式 1我方承担 2客户承担 3双方平摊 4月结',
    `base_amount` decimal(24,6) DEFAULT 0 COMMENT '铺底金额',
    `task_amount` decimal(24,6) DEFAULT 0 COMMENT '目标任务量',
    `summary` text DEFAULT NULL COMMENT '摘要',
    `attachment_url` varchar(512) DEFAULT NULL COMMENT '合同附件',
    `status` tinyint DEFAULT 0 COMMENT '状态',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_supplier_contract_supplier_id` (`supplier_id`),
    KEY `idx_supplier_contract_no` (`contract_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商合同';

CREATE TABLE IF NOT EXISTS `erp_supplier_extend_info` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `chain_group_id` bigint DEFAULT NULL COMMENT '对应连锁',
    `bank_name2` varchar(128) DEFAULT NULL COMMENT '开户行2',
    `bank_account2` varchar(64) DEFAULT NULL COMMENT '账户2',
    `ext_email` varchar(128) DEFAULT NULL COMMENT '电子邮件',
    `id_card_no` varchar(32) DEFAULT NULL COMMENT '身份证号码',
    `alternate_code` varchar(64) DEFAULT NULL COMMENT '替代编码',
    `base_amount` decimal(18,2) DEFAULT 0 COMMENT '铺底金额',
    `legal_person` varchar(64) DEFAULT NULL COMMENT '企业法人',
    `legal_person_phone` varchar(32) DEFAULT NULL COMMENT '法人电话',
    `boss` varchar(64) DEFAULT NULL COMMENT '老板',
    `boss_phone` varchar(32) DEFAULT NULL COMMENT '老板电话',
    `price_markup_rate` decimal(10,4) DEFAULT NULL COMMENT '浮动率',
    `key_supplier` bit(1) DEFAULT b'0' COMMENT '重点供应商',
    `alliance_replenishment` bit(1) DEFAULT b'0' COMMENT '联盟补货',
    `purchase_return_contact` varchar(64) DEFAULT NULL COMMENT '采购退货联系人',
    `purchase_return_address` varchar(500) DEFAULT NULL COMMENT '采购退货地址',
    `purchase_return_phone` varchar(32) DEFAULT NULL COMMENT '采购退货电话',
    `settle_day` int DEFAULT NULL COMMENT '结账日期',
    `generate_in_bill` bit(1) DEFAULT b'0' COMMENT '是否产生入仓单',
    `inbound_method` varchar(64) DEFAULT NULL COMMENT '入库方式',
    `generate_label_task` bit(1) DEFAULT b'0' COMMENT '是否产生贴码任务',
    `alliance_order_match_rule` text DEFAULT NULL COMMENT '联盟商开单匹配规则',
    `alliance_bill_extract_rule` text DEFAULT NULL COMMENT '联盟商单据提取规则',
    `settle_account_id` bigint DEFAULT NULL COMMENT '结算账户编号',
    `scrap_return_cycle_days` int DEFAULT NULL COMMENT '废品返厂周期',
    `scrap_return_next_date` date DEFAULT NULL COMMENT '返厂下次计算日期',
    `scrap_return_threshold_amount` decimal(18,2) DEFAULT NULL COMMENT '废品返厂阈值金额',
    `auto_replenishment_enabled` bit(1) DEFAULT b'0' COMMENT '启用自动补货',
    `auto_replenishment_formula` varchar(64) DEFAULT NULL COMMENT '自动补货公式',
    `auto_replenishment_cycle` varchar(128) DEFAULT NULL COMMENT '自动补货周期',
    `auto_replenishment_time` time DEFAULT NULL COMMENT '自动补货时间',
    `next_order_date` date DEFAULT NULL COMMENT '下次订货日期',
    `stock_upper_days` int DEFAULT NULL COMMENT '库存上限天数',
    `stock_standard_days` int DEFAULT NULL COMMENT '标准库存天数',
    `stock_lower_days` int DEFAULT NULL COMMENT '库存下限天数',
    `daily_sale_cycle` varchar(64) DEFAULT NULL COMMENT '日均销售周期',
    `daily_sale_recent_days` int DEFAULT NULL COMMENT '日均销量距今',
    `limit_adjust_recent_months` int DEFAULT NULL COMMENT '上下限调整条件-最近月数',
    `limit_adjust_monthly_sales` decimal(18,2) DEFAULT NULL COMMENT '上下限调整条件-月均销量',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_supplier_extend_info_supplier_id` (`supplier_id`, `tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商结构化拓展信息';

CREATE TABLE IF NOT EXISTS `erp_supplier_extend` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `extend_key` varchar(64) NOT NULL COMMENT '字段标识',
    `extend_name` varchar(128) DEFAULT NULL COMMENT '字段名称',
    `extend_value` text DEFAULT NULL COMMENT '字段值',
    `extend_type` varchar(64) DEFAULT NULL COMMENT '字段类型',
    `required` bit(1) DEFAULT b'0' COMMENT '是否必填',
    `option_values` varchar(1000) DEFAULT NULL COMMENT '下拉选项值',
    `sort` int DEFAULT 0 COMMENT '排序',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_supplier_extend_supplier_id` (`supplier_id`),
    KEY `idx_supplier_extend_key` (`extend_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商动态拓展字段';

CREATE TABLE IF NOT EXISTS `erp_supplier_image` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `image_type` varchar(64) NOT NULL COMMENT '图片类型',
    `image_name` varchar(128) DEFAULT NULL COMMENT '图片名称',
    `image_url` varchar(512) NOT NULL COMMENT '图片地址',
    `defaulted` bit(1) DEFAULT b'0' COMMENT '默认图',
    `sort` int DEFAULT 0 COMMENT '排序',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_supplier_image_supplier_id` (`supplier_id`),
    KEY `idx_supplier_image_type` (`image_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商企业图片';

CREATE TABLE IF NOT EXISTS `erp_supplier_account` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `account_name` varchar(128) NOT NULL COMMENT '账户名',
    `card_no` varchar(64) NOT NULL COMMENT '卡号',
    `bank_name` varchar(128) DEFAULT NULL COMMENT '开户行',
    `defaulted` bit(1) DEFAULT b'0' COMMENT '默认账户',
    `sort` int DEFAULT 0 COMMENT '排序',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_supplier_account_supplier_id` (`supplier_id`),
    KEY `idx_supplier_account_card_no` (`card_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商账户';

CREATE TABLE IF NOT EXISTS `erp_supplier_bill` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `bill_date` date NOT NULL COMMENT '票据登记日期',
    `bill_no` varchar(64) NOT NULL COMMENT '票据号',
    `amount` decimal(18,2) NOT NULL COMMENT '金额',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_supplier_bill_supplier_id` (`supplier_id`),
    KEY `idx_supplier_bill_no` (`bill_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商票据登记';

CREATE TABLE IF NOT EXISTS `erp_supplier_task` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `year` int NOT NULL COMMENT '年份',
    `month` int NOT NULL COMMENT '月份',
    `task_level` varchar(64) DEFAULT NULL COMMENT '任务级别',
    `task_amount` decimal(24,6) NOT NULL COMMENT '任务量',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_supplier_task_period` (`supplier_id`, `year`, `month`, `task_level`, `tenant_id`, `deleted`),
    KEY `idx_supplier_task_supplier_id` (`supplier_id`),
    KEY `idx_supplier_task_period` (`year`, `month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商任务量';

CREATE TABLE IF NOT EXISTS `erp_supplier_business_info` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `supplier_id` bigint NOT NULL COMMENT '供应商编号',
    `company_name` varchar(128) DEFAULT NULL COMMENT '企业名称',
    `credit_code` varchar(64) DEFAULT NULL COMMENT '统一信用代码',
    `legal_person` varchar(64) DEFAULT NULL COMMENT '法定代表人',
    `registered_address` varchar(500) DEFAULT NULL COMMENT '注册地址',
    `business_scope` text DEFAULT NULL COMMENT '经营范围',
    `registered_capital` varchar(64) DEFAULT NULL COMMENT '注册资本',
    `establish_date` varchar(64) DEFAULT NULL COMMENT '成立日期',
    `business_status` varchar(64) DEFAULT NULL COMMENT '经营状态',
    `raw_data` longtext DEFAULT NULL COMMENT '第三方原始数据',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_supplier_business_info_supplier_id` (`supplier_id`),
    KEY `idx_supplier_business_info_credit_code` (`credit_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 供应商工商信息';
