-- 八期：销售模块报价订单、销售手推车、销售单来源字段、客户基础档案扩展
-- 执行前请确认目标库已完成采购库存 v1-v7 脚本。

ALTER TABLE `erp_customer`
    ADD COLUMN `code` varchar(64) DEFAULT NULL COMMENT '客户编码' AFTER `id`,
    ADD COLUMN `old_code` varchar(64) DEFAULT NULL COMMENT '旧编码' AFTER `code`,
    ADD COLUMN `short_name` varchar(128) DEFAULT NULL COMMENT '简称' AFTER `name`,
    ADD COLUMN `foreign_name` varchar(128) DEFAULT NULL COMMENT '外文名' AFTER `short_name`,
    ADD COLUMN `relation_type` tinyint DEFAULT NULL COMMENT '往来类别' AFTER `foreign_name`,
    ADD COLUMN `area_id` bigint DEFAULT NULL COMMENT '区域编号' AFTER `relation_type`,
    ADD COLUMN `customer_type` tinyint DEFAULT NULL COMMENT '客户类型' AFTER `area_id`,
    ADD COLUMN `company_nature` varchar(64) DEFAULT NULL COMMENT '公司性质' AFTER `customer_type`,
    ADD COLUMN `group_customer` bit(1) DEFAULT b'0' COMMENT '是否集团客户' AFTER `company_nature`,
    ADD COLUMN `enterprise_match_status` tinyint DEFAULT NULL COMMENT '企业匹配状态' AFTER `group_customer`,
    ADD COLUMN `finance_telephone` varchar(32) DEFAULT NULL COMMENT '财务联系电话' AFTER `fax`,
    ADD COLUMN `address_area_id` bigint DEFAULT NULL COMMENT '地址区域编号' AFTER `finance_telephone`,
    ADD COLUMN `address` varchar(255) DEFAULT NULL COMMENT '地址' AFTER `address_area_id`,
    ADD COLUMN `detail_address` varchar(255) DEFAULT NULL COMMENT '详细地址' AFTER `address`,
    ADD COLUMN `post_code` varchar(16) DEFAULT NULL COMMENT '邮政编码' AFTER `detail_address`,
    ADD COLUMN `delivery_area` tinyint DEFAULT NULL COMMENT '发货区' AFTER `post_code`,
    ADD COLUMN `arrival_point` varchar(128) DEFAULT NULL COMMENT '到货点' AFTER `delivery_area`,
    ADD COLUMN `account_name` varchar(128) DEFAULT NULL COMMENT '账户' AFTER `tax_no`,
    ADD COLUMN `settle_method` tinyint DEFAULT NULL COMMENT '结算方式' AFTER `account_name`,
    ADD COLUMN `settle_locked` bit(1) DEFAULT b'0' COMMENT '结算锁定' AFTER `settle_method`,
    ADD COLUMN `invoice_type` tinyint DEFAULT NULL COMMENT '开票类型' AFTER `settle_locked`,
    ADD COLUMN `min_order_amount` decimal(24,6) DEFAULT NULL COMMENT '起订金额' AFTER `invoice_type`,
    ADD COLUMN `freight_type` tinyint DEFAULT NULL COMMENT '运费类型' AFTER `min_order_amount`,
    ADD COLUMN `commission_rate` decimal(24,6) DEFAULT NULL COMMENT '佣金比例' AFTER `freight_type`,
    ADD COLUMN `commission_enabled` bit(1) DEFAULT b'0' COMMENT '启用佣金机制' AFTER `commission_rate`,
    ADD COLUMN `unified_credit_code` varchar(64) DEFAULT NULL COMMENT '统一信用代码' AFTER `bank_address`,
    ADD COLUMN `invoice_bank_name` varchar(128) DEFAULT NULL COMMENT '开票银行' AFTER `unified_credit_code`,
    ADD COLUMN `invoice_bank_account` varchar(128) DEFAULT NULL COMMENT '开票银行账号' AFTER `invoice_bank_name`,
    ADD COLUMN `invoice_address` varchar(255) DEFAULT NULL COMMENT '开票地址' AFTER `invoice_bank_account`,
    ADD COLUMN `invoice_telephone` varchar(32) DEFAULT NULL COMMENT '开票电话' AFTER `invoice_address`,
    ADD COLUMN `invoice_company` varchar(128) DEFAULT NULL COMMENT '开票单位' AFTER `invoice_telephone`,
    ADD COLUMN `sale_user_id` bigint DEFAULT NULL COMMENT '所属业务员' AFTER `invoice_company`,
    ADD COLUMN `developer_user_id` bigint DEFAULT NULL COMMENT '所属开发员' AFTER `sale_user_id`,
    ADD COLUMN `dept_id` bigint DEFAULT NULL COMMENT '所属部门' AFTER `developer_user_id`,
    ADD COLUMN `price_level` tinyint DEFAULT NULL COMMENT '价格级别' AFTER `dept_id`,
    ADD COLUMN `price_locked` bit(1) DEFAULT b'0' COMMENT '价格锁定' AFTER `price_level`,
    ADD COLUMN `profit_reference_price_level` tinyint DEFAULT NULL COMMENT '绩效利润参考依据' AFTER `price_locked`,
    ADD COLUMN `ecommerce_payment` tinyint DEFAULT NULL COMMENT '电商支付' AFTER `profit_reference_price_level`,
    ADD COLUMN `logistics` bit(1) DEFAULT b'0' COMMENT '是否物流' AFTER `ecommerce_payment`,
    ADD COLUMN `transport_method` tinyint DEFAULT NULL COMMENT '运输方式' AFTER `logistics`,
    ADD COLUMN `route_id` bigint DEFAULT NULL COMMENT '线路编号' AFTER `transport_method`,
    ADD COLUMN `freight_explain_id` bigint DEFAULT NULL COMMENT '运费说明编号' AFTER `route_id`,
    ADD COLUMN `wubi_code` varchar(64) DEFAULT NULL COMMENT '五笔码' AFTER `freight_explain_id`,
    ADD COLUMN `pinyin_code` varchar(64) DEFAULT NULL COMMENT '拼音码' AFTER `wubi_code`,
    ADD COLUMN `member_code` varchar(64) DEFAULT NULL COMMENT '会员编码' AFTER `pinyin_code`,
    ADD COLUMN `platform_code` varchar(64) DEFAULT NULL COMMENT '平台唯一码' AFTER `member_code`;

ALTER TABLE `erp_sale_out`
    ADD COLUMN `source_type` tinyint DEFAULT NULL COMMENT '业务来源类型（10旧销售订单 20报价订单 30销售手推车）' AFTER `order_no`,
    ADD COLUMN `source_id` bigint DEFAULT NULL COMMENT '来源单据编号' AFTER `source_type`,
    ADD COLUMN `source_no` varchar(64) DEFAULT NULL COMMENT '来源单据号' AFTER `source_id`;

CREATE TABLE `erp_sale_quote` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NOT NULL COMMENT '报价单号',
    `status` tinyint NOT NULL COMMENT '状态',
    `customer_id` bigint NOT NULL COMMENT '客户编号',
    `account_id` bigint DEFAULT NULL COMMENT '结算账户编号',
    `sale_user_id` bigint DEFAULT NULL COMMENT '销售员编号',
    `dept_id` bigint DEFAULT NULL COMMENT '部门编号',
    `quote_time` datetime NOT NULL COMMENT '报价时间',
    `total_count` decimal(24,6) DEFAULT NULL COMMENT '合计数量',
    `total_price` decimal(24,6) DEFAULT NULL COMMENT '合计金额',
    `total_product_price` decimal(24,6) DEFAULT NULL COMMENT '合计产品金额',
    `total_tax_price` decimal(24,6) DEFAULT NULL COMMENT '合计税额',
    `discount_percent` decimal(24,6) DEFAULT NULL COMMENT '优惠率',
    `discount_price` decimal(24,6) DEFAULT NULL COMMENT '优惠金额',
    `other_price` decimal(24,6) DEFAULT NULL COMMENT '其它金额',
    `source_type` tinyint DEFAULT NULL COMMENT '业务来源类型（10旧销售订单 20报价订单 30销售手推车）',
    `source_id` bigint DEFAULT NULL COMMENT '来源单据编号',
    `source_no` varchar(64) DEFAULT NULL COMMENT '来源单据号',
    `file_url` varchar(512) DEFAULT NULL COMMENT '附件地址',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_sale_quote_no` (`no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 报价订单';

CREATE TABLE `erp_sale_quote_items` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `quote_id` bigint NOT NULL COMMENT '报价订单编号',
    `product_id` bigint NOT NULL COMMENT '产品编号',
    `product_unit_id` bigint DEFAULT NULL COMMENT '产品单位编号',
    `warehouse_id` bigint NOT NULL COMMENT '仓库编号',
    `product_price` decimal(24,6) DEFAULT NULL COMMENT '产品单价',
    `count` decimal(24,6) NOT NULL COMMENT '数量',
    `converted_count` decimal(24,6) DEFAULT 0 COMMENT '已转数量',
    `total_price` decimal(24,6) DEFAULT NULL COMMENT '总价',
    `tax_percent` decimal(24,6) DEFAULT NULL COMMENT '税率',
    `tax_price` decimal(24,6) DEFAULT NULL COMMENT '税额',
    `warehouse_position` varchar(128) DEFAULT NULL COMMENT '货架位',
    `drawing_no` varchar(128) DEFAULT NULL COMMENT '图号',
    `batch_no` varchar(128) DEFAULT NULL COMMENT '批次号',
    `bar_code` varchar(128) DEFAULT NULL COMMENT '条码',
    `brand` varchar(128) DEFAULT NULL COMMENT '品牌',
    `vehicle_model` varchar(128) DEFAULT NULL COMMENT '车型',
    `origin_place` varchar(128) DEFAULT NULL COMMENT '产地',
    `standard` varchar(128) DEFAULT NULL COMMENT '规格',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_sale_quote_items_quote_id` (`quote_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 报价订单项';

CREATE TABLE `erp_sale_cart` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `no` varchar(64) NOT NULL COMMENT '手推车单号',
    `status` tinyint NOT NULL COMMENT '状态',
    `customer_id` bigint NOT NULL COMMENT '客户编号',
    `account_id` bigint DEFAULT NULL COMMENT '结算账户编号',
    `sale_user_id` bigint DEFAULT NULL COMMENT '销售员编号',
    `dept_id` bigint DEFAULT NULL COMMENT '部门编号',
    `cart_time` datetime NOT NULL COMMENT '开单时间',
    `first_audit_user_id` bigint DEFAULT NULL COMMENT '初审人',
    `first_audit_time` datetime DEFAULT NULL COMMENT '初审时间',
    `final_audit_user_id` bigint DEFAULT NULL COMMENT '终审人',
    `final_audit_time` datetime DEFAULT NULL COMMENT '终审时间',
    `total_count` decimal(24,6) DEFAULT NULL COMMENT '合计数量',
    `total_price` decimal(24,6) DEFAULT NULL COMMENT '合计金额',
    `total_product_price` decimal(24,6) DEFAULT NULL COMMENT '合计产品金额',
    `total_tax_price` decimal(24,6) DEFAULT NULL COMMENT '合计税额',
    `discount_percent` decimal(24,6) DEFAULT NULL COMMENT '优惠率',
    `discount_price` decimal(24,6) DEFAULT NULL COMMENT '优惠金额',
    `other_price` decimal(24,6) DEFAULT NULL COMMENT '其它金额',
    `source_type` tinyint DEFAULT NULL COMMENT '业务来源类型（10旧销售订单 20报价订单 30销售手推车）',
    `source_id` bigint DEFAULT NULL COMMENT '来源单据编号',
    `source_no` varchar(64) DEFAULT NULL COMMENT '来源单据号',
    `file_url` varchar(512) DEFAULT NULL COMMENT '附件地址',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_sale_cart_no` (`no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 销售手推车';

CREATE TABLE `erp_sale_cart_items` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `cart_id` bigint NOT NULL COMMENT '销售手推车编号',
    `product_id` bigint NOT NULL COMMENT '产品编号',
    `product_unit_id` bigint DEFAULT NULL COMMENT '产品单位编号',
    `warehouse_id` bigint NOT NULL COMMENT '仓库编号',
    `product_price` decimal(24,6) DEFAULT NULL COMMENT '产品单价',
    `count` decimal(24,6) NOT NULL COMMENT '数量',
    `total_price` decimal(24,6) DEFAULT NULL COMMENT '总价',
    `tax_percent` decimal(24,6) DEFAULT NULL COMMENT '税率',
    `tax_price` decimal(24,6) DEFAULT NULL COMMENT '税额',
    `stock_count` decimal(24,6) DEFAULT NULL COMMENT '开单时库存',
    `warehouse_position` varchar(128) DEFAULT NULL COMMENT '货架位',
    `drawing_no` varchar(128) DEFAULT NULL COMMENT '图号',
    `batch_no` varchar(128) DEFAULT NULL COMMENT '批次号',
    `bar_code` varchar(128) DEFAULT NULL COMMENT '条码',
    `brand` varchar(128) DEFAULT NULL COMMENT '品牌',
    `vehicle_model` varchar(128) DEFAULT NULL COMMENT '车型',
    `origin_place` varchar(128) DEFAULT NULL COMMENT '产地',
    `standard` varchar(128) DEFAULT NULL COMMENT '规格',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_sale_cart_items_cart_id` (`cart_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 销售手推车项';

CREATE TABLE `erp_sale_convert_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `convert_type` tinyint NOT NULL COMMENT '转换类型（10报价转手推车 20手推车转报价）',
    `source_type` tinyint NOT NULL COMMENT '来源类型',
    `source_id` bigint NOT NULL COMMENT '来源单据编号',
    `source_no` varchar(64) NOT NULL COMMENT '来源单据号',
    `source_item_id` bigint DEFAULT NULL COMMENT '来源明细编号',
    `target_type` tinyint NOT NULL COMMENT '目标类型',
    `target_id` bigint DEFAULT NULL COMMENT '目标单据编号',
    `target_no` varchar(64) DEFAULT NULL COMMENT '目标单据号',
    `target_item_id` bigint DEFAULT NULL COMMENT '目标明细编号',
    `product_id` bigint NOT NULL COMMENT '产品编号',
    `warehouse_id` bigint DEFAULT NULL COMMENT '仓库编号',
    `count` decimal(24,6) NOT NULL COMMENT '转换数量',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_sale_convert_source` (`source_type`, `source_id`),
    KEY `idx_sale_convert_target` (`target_type`, `target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP 销售单据转换记录';
