-- 经营报表1/4不可变交易行快照；仅新建，不回填历史，不授予角色权限。
CREATE TABLE IF NOT EXISTS erp_business_report_item_snapshot (
 tenant_id BIGINT NOT NULL,
 posting_id BIGINT NOT NULL,
 posted_at DATETIME(6) NOT NULL,
 signature CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 business_type VARCHAR(32) NOT NULL,
 biz_id BIGINT NOT NULL,
 biz_item_id BIGINT NOT NULL,
 party_id BIGINT NULL,
 party_name VARCHAR(255) NULL,
 sale_user_id BIGINT NULL,
 sale_user_name VARCHAR(255) NULL,
 accounting_dept_name VARCHAR(255) NULL,
 stock_dept_name VARCHAR(255) NULL,
 warehouse_name VARCHAR(255) NULL,
 purchaser VARCHAR(255) NULL,
 source_creator VARCHAR(64) NULL,
 product_code VARCHAR(255) NULL,
 product_name VARCHAR(255) NULL,
 oe_number VARCHAR(255) NULL,
 brand VARCHAR(255) NULL,
 category_id BIGINT NULL,
 unit_name VARCHAR(128) NULL,
 specification VARCHAR(255) NULL,
 raw_gross_amount DECIMAL(24,6) NULL,
 gross_amount DECIMAL(24,6) NULL,
 net_amount DECIMAL(24,6) NULL,
 gross_status VARCHAR(64) NOT NULL,
 original_biz_id BIGINT NULL,
 original_biz_item_id BIGINT NULL,
 original_biz_no VARCHAR(128) NULL,
 no_original_sale TINYINT NULL,
 snapshot_json LONGTEXT NOT NULL,
 PRIMARY KEY(tenant_id,posting_id),
 KEY idx_trade_party (tenant_id,business_type,party_id,posted_at),
 KEY idx_trade_source (tenant_id,business_type,biz_id,biz_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='真实过账同事务交易快照；金额未知不补零，禁止修改历史';
