-- 报表计划 00/03 基础阶段。仅建新表，不回填旧成本，不启用新核算，不修改业务或权限数据。
-- 必须逐库存核对期初；所有业务类型接入前，erp.reporting.dual-cost-enabled 保持 false。
CREATE TABLE IF NOT EXISTS erp_stock_dual_cost_balance (
  tenant_id BIGINT NOT NULL,
  stock_id BIGINT NOT NULL,
  quantity DECIMAL(24,6) NOT NULL,
  financial_amount DECIMAL(24,6) NOT NULL,
  settlement_amount DECIMAL(24,6) NOT NULL,
  opening_quantity DECIMAL(24,6) NOT NULL,
  opening_financial_amount DECIMAL(24,6) NOT NULL,
  opening_settlement_amount DECIMAL(24,6) NOT NULL,
  cutover_at DATETIME NOT NULL,
  confirmed_by BIGINT NOT NULL,
  confirmed_at DATETIME(6) NOT NULL,
  evidence VARCHAR(500) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  legacy_record_id BIGINT NOT NULL COMMENT '核对或最近自身过账后的原库存流水水位',
  legacy_cost_price DECIMAL(24,6) NULL,
  legacy_cost_amount DECIMAL(24,6) NULL,
  stock_dept_id BIGINT NOT NULL,
  PRIMARY KEY (tenant_id,stock_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='核对期初及双成本余额，禁止覆盖原始期初';

CREATE TABLE IF NOT EXISTS erp_stock_dual_cost_posting (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL,
  action_key VARCHAR(160) COLLATE utf8mb4_bin NOT NULL,
  request_hash CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  stock_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  stock_dept_id BIGINT NOT NULL,
  accounting_dept_id BIGINT NOT NULL,
  biz_type INT NOT NULL,
  biz_id BIGINT NOT NULL,
  biz_item_id BIGINT NOT NULL,
  biz_no VARCHAR(128) NOT NULL,
  source_biz_type INT NULL,
  source_biz_id BIGINT NULL,
  source_biz_item_id BIGINT NULL,
  reversal_posting_id BIGINT NULL,
  biz_date DATETIME NOT NULL,
  posted_at DATETIME(6) NOT NULL,
  quantity DECIMAL(24,6) NOT NULL,
  financial_movement DECIMAL(24,6) NOT NULL,
  settlement_movement DECIMAL(24,6) NOT NULL,
  balance_quantity DECIMAL(24,6) NOT NULL,
  financial_balance DECIMAL(24,6) NOT NULL,
  settlement_balance DECIMAL(24,6) NOT NULL,
  rule_version VARCHAR(64) NOT NULL,
  raw_unit_price DECIMAL(24,6) NULL COMMENT '原始业务录入单价，禁止当成未税成本',
  source_price_basis VARCHAR(64) NULL COMMENT '含税待确认等来源口径',
  batch_no VARCHAR(128) NULL,
  posted_by BIGINT NULL COMMENT '系统触发时允许为空',
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_action (tenant_id,action_key),
  KEY idx_tenant_stock_posted (tenant_id,stock_id,posted_at,id),
  KEY idx_tenant_source (tenant_id,source_biz_type,source_biz_id,source_biz_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='追加式双成本过账事件，业务日期与过账时间分离';
