-- Sale management form field permission definitions.
-- Scope: main form fields, detail-item columns, sale internal selection modal fields,
-- customer form fields, and sale config form fields.
-- List search fields and list table columns are intentionally excluded.

CREATE TABLE IF NOT EXISTS `system_field_definition` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `module` VARCHAR(50) NOT NULL COMMENT 'Module key',
  `field_key` VARCHAR(100) NOT NULL COMMENT 'Field key',
  `field_label` VARCHAR(100) NOT NULL COMMENT 'Field label',
  `field_group` VARCHAR(50) DEFAULT NULL COMMENT 'Field group',
  `sort` INT NOT NULL DEFAULT 0 COMMENT 'Sort',
  `creator` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_module_field` (`module`, `field_key`, `tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System field definition';

CREATE TABLE IF NOT EXISTS `system_role_field_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `role_id` BIGINT NOT NULL COMMENT 'Role id',
  `field_id` BIGINT NOT NULL COMMENT 'Field definition id',
  `hidden` BIT(1) NOT NULL DEFAULT b'1' COMMENT 'Whether hidden',
  `creator` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_field` (`role_id`, `field_id`, `tenant_id`, `deleted`),
  KEY `idx_field_id` (`field_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System role field permission';

DELETE rfp
FROM `system_role_field_permission` rfp
JOIN `system_field_definition` fd ON fd.id = rfp.field_id
WHERE fd.module IN (
    'erp_sale_quote', 'erp_sale_order', 'erp_sale_cart', 'erp_sale_out',
    'erp_sale_return', 'erp_sale_price_adjust', 'erp_customer', 'erp_sale_config'
  )
  AND (
    fd.field_group IN ('list_col', 'search', 'search_info')
    OR fd.field_key LIKE 'col\_%'
    OR fd.field_key LIKE 'search\_%'
  );

UPDATE `system_field_definition`
SET `deleted` = b'1',
    `updater` = '1',
    `update_time` = NOW()
WHERE `module` IN (
    'erp_sale_quote', 'erp_sale_order', 'erp_sale_cart', 'erp_sale_out',
    'erp_sale_return', 'erp_sale_price_adjust', 'erp_customer', 'erp_sale_config'
  )
  AND (
    `field_group` IN ('list_col', 'search', 'search_info')
    OR `field_key` LIKE 'col\_%'
    OR `field_key` LIKE 'search\_%'
  );

INSERT INTO `system_field_definition`
(`module`, `field_key`, `field_label`, `field_group`, `sort`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
('erp_sale_quote', 'no', '报价单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'quoteTime', '报价时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'customerId', '客户', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'orderType', '订单类型', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'saleUserId', '业务员', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'settleMethod', '结算方式', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'prepayment', '先款后货', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'accountId', '结算账户', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'priority', '优先级', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'deliveryMethod', '送货方式', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'proxyDelivery', '代客户发货', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'deliveryAddress', '收货地址', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'allowancePrice', '折让金额', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'ticketNo', '票据号', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'invoiceType', '开票类型', 'main_form', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'freightType', '运费类型', 'main_form', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'freightAmount', '费用金额', 'main_form', 170, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'logisticsCompany', '物流公司', 'main_form', 180, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'deptId', '部门', 'main_form', 190, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'receiverName', '收货人', 'main_form', 200, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'receiverPhone', '收货电话', 'main_form', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'priceType', '价格类型', 'main_form', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'branchDelivery', '分店发货', 'main_form', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'expectedDeliveryTime', '预计发货时间', 'main_form', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'billingMethod', '开单方式', 'main_form', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'vehiclePlateNo', '车牌号', 'main_form', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'businessType', '业务类型', 'main_form', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'developerUserId', '开发员', 'main_form', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'vin', '车架号', 'main_form', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'remark', '备注', 'main_form', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'internalRemark', '内部备注', 'main_form', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_productId', '产品名称', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_warehouseId', '仓库', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_count', '数量', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_productPrice', '产品单价', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_giftFlag', '是否为赠品', 'detail_item', 435, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_stockCount', '库存', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_productBarCode', '条码', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_productUnitName', '单位', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_brand', '品牌', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_vehicleModel', '车型', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_originPlace', '产地', 'detail_item', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_standard', '规格', 'detail_item', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_convertedCount', '已转数量', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_totalPrice', '合计金额', 'detail_item', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_taxPercent', '税率', 'detail_item', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_taxPrice', '税额', 'detail_item', 540, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_taxInclusivePrice', '含税单价', 'detail_item', 550, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_taxInclusiveAmount', '含税金额', 'detail_item', 560, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'item_remark', '备注', 'detail_item', 570, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'select_customerName', '转换客户', 'select_modal', 700, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'select_saleUserId', '转换业务员', 'select_modal', 710, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_quote', 'select_remark', '转换备注', 'select_modal', 720, '1', NOW(), '1', NOW(), b'0', 1),

('erp_sale_order', 'no', '订单单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'orderTime', '订单时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'customerId', '客户', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'orderType', '订单类型', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'saleUserId', '业务员', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'remark', '备注', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'fileUrl', '附件', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'discountPercent', '优惠率', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'discountPrice', '优惠金额', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'totalPrice', '合计金额', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'accountId', '结算账户', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'depositPrice', '订金', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_productId', '产品名称', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_stockCount', '库存', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_productBarCode', '条码', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_productUnitName', '单位', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_giftFlag', '赠品', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_remark', '备注', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_count', '数量', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_productPrice', '产品单价', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_totalProductPrice', '产品金额', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_taxPercent', '税率', 'detail_item', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_taxPrice', '税额', 'detail_item', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_order', 'item_totalPrice', '合计金额', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),

('erp_sale_cart', 'customerId', '客户', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'saleUserId', '业务员', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'accountId', '结算账户', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'quoteId', '来源报价单', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'quoteNo', '来源报价号', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'fileUrl', '附件', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'remark', '备注', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'totalPrice', '合计金额', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'discountPrice', '优惠金额', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'depositPrice', '订金', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_productId', '产品名称', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_warehouseId', '仓库', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_count', '数量', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_productPrice', '产品单价', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_giftFlag', '是否为赠品', 'detail_item', 435, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_totalProductPrice', '产品金额', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_taxPercent', '税率', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_taxPrice', '税额', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_totalPrice', '合计金额', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_stockCount', '库存', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_productBarCode', '条码', 'detail_item', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_productUnitName', '单位', 'detail_item', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_brand', '品牌', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_vehicleModel', '车型', 'detail_item', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_standard', '规格', 'detail_item', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_cart', 'item_remark', '备注', 'detail_item', 540, '1', NOW(), '1', NOW(), b'0', 1),

('erp_sale_out', 'no', '出库单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'sourceNo', '来源单号', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'customerId', '客户', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'saleUserId', '业务员', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'outTime', '出库时间', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'accountId', '结算账户', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'totalCount', '合计数量', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'totalProductPrice', '产品金额', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'totalPrice', '应收金额', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'remark', '备注', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'fileUrl', '附件', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_productCode', '产品编码', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_productName', '产品名称', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_vehicleModel', '车型', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_standard', '规格', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_featureCode', '特征码', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_brand', '品牌', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_productUnitName', '单位', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_count', '数量', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_productPrice', '单价', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_totalProductPrice', '产品金额', 'detail_item', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_actualSaleAmount', '实销金额', 'detail_item', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_drawingNo', '图号', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_batchNo', '批次', 'detail_item', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_warehouseName', '仓库', 'detail_item', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_warehousePosition', '货位', 'detail_item', 540, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_unitWeight', '单重', 'detail_item', 550, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_totalWeight', '总重', 'detail_item', 560, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_afterReductionPrice', '折后单价', 'detail_item', 570, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_afterReductionAmount', '折后金额', 'detail_item', 580, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_originPlace', '产地', 'detail_item', 590, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_supplierName', '供应商', 'detail_item', 600, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_remark', '备注', 'detail_item', 610, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_out', 'item_originalProductPrice', '原单价', 'detail_item', 620, '1', NOW(), '1', NOW(), b'0', 1),

('erp_sale_return', 'returnMode', '退货模式', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'no', '退货单号', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'returnTime', '退货时间', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'orderNo', '来源销售单', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'outNo', '来源出库单', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'customerId', '客户', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'saleUserId', '业务员', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'handler', '经手人', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'deptId', '部门', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'accountId', '结算账户', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'refundPrice', '退款金额', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'freightAmount', '运费金额', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'invoiceType', '开票类型', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'remark', '备注', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'fileUrl', '附件', 'main_form', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_productId', '产品名称', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_warehouseId', '仓库', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_count', '数量', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_productPrice', '单价', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_totalProductPrice', '产品金额', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_outCount', '出库数量', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_returnableCount', '可退数量', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_returnedCount', '已退数量', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_taxPercent', '税率', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_taxPrice', '税额', 'detail_item', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_totalPrice', '价税合计', 'detail_item', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'item_remark', '备注', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'select_col_no', '选择单号', 'select_modal', 700, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'select_col_customerName', '选择客户', 'select_modal', 710, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'select_col_totalPrice', '选择金额', 'select_modal', 720, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_return', 'select_col_productNames', '选择产品', 'select_modal', 730, '1', NOW(), '1', NOW(), b'0', 1),

('erp_sale_price_adjust', 'no', '调价单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'adjustTime', '调价时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'adjustType', '调价方式', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'customerId', '客户', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'deptId', '部门', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'adjuster', '调价人', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'totalAdjustPrice', '调价总额', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'remark', '备注', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_outNo', '来源出库单', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_productCode', '产品编码', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_productName', '产品名称', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_vehicleModel', '车型', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_standard', '规格', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_brand', '品牌', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_count', '数量', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_oldPrice', '原价格', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_newPrice', '新价格', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_adjustRatio', '调价比例', 'detail_item', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'item_adjustPrice', '调价金额', 'detail_item', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'select_col_outNo', '出库单号', 'select_modal', 700, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'select_col_customerName', '客户', 'select_modal', 710, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'select_col_productName', '产品名称', 'select_modal', 720, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_price_adjust', 'select_col_productPrice', '原价格', 'select_modal', 730, '1', NOW(), '1', NOW(), b'0', 1),

('erp_customer', 'code', '客户编码', 'basic_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'name', '客户名称', 'basic_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'shortName', '简称', 'basic_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'relationType', '往来类别', 'basic_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'areaId', '所属区域', 'basic_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'customerType', '客户类型', 'basic_info', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'groupCustomer', '集团客户', 'basic_info', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'enterpriseMatchStatus', '企业匹配状态', 'basic_info', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'contact', '联系人', 'contact_info', 200, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'telephone', '联系电话', 'contact_info', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'mobile', '手机号', 'contact_info', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'financeTelephone', '财务电话', 'contact_info', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'addressAreaId', '地址区域', 'contact_info', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'detailAddress', '详细地址', 'contact_info', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'postCode', '邮政编码', 'contact_info', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'accountName', '账户名称', 'finance_info', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'settleMethod', '结算方式', 'finance_info', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'settleLocked', '结算锁定', 'finance_info', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'invoiceType', '发票类型', 'finance_info', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'minOrderAmount', '最低订单金额', 'finance_info', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'freightType', '运费类型', 'finance_info', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'commissionRate', '提成比例', 'finance_info', 360, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'commissionEnabled', '启用提成', 'finance_info', 370, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'unifiedCreditCode', '统一信用代码', 'invoice_info', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'taxNo', '税号', 'invoice_info', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'bankName', '开户行', 'invoice_info', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'invoiceBankName', '开票银行', 'invoice_info', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'invoiceBankAccount', '开票银行账号', 'invoice_info', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'invoiceAddress', '开票地址', 'invoice_info', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'invoiceTelephone', '开票电话', 'invoice_info', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'invoiceCompany', '开票单位', 'invoice_info', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'bankAccount', '银行账号', 'invoice_info', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'bankAddress', '开户地址', 'invoice_info', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'saleUserId', '业务员', 'sale_info', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'developerUserId', '开发员', 'sale_info', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'deptId', '部门', 'sale_info', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'priceLevel', '价格等级', 'sale_info', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'priceLocked', '价格锁定', 'sale_info', 540, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'creditLimit', '信用额度', 'sale_info', 590, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'dataCenterAuditStatus', '数据中心审核状态', 'sale_info', 600, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'logistics', '物流公司', 'logistics_info', 700, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'transportMethod', '运输方式', 'logistics_info', 710, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'routeId', '线路', 'logistics_info', 720, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'freightExplainId', '运费说明', 'logistics_info', 730, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'wubiCode', '五笔码', 'system_info', 800, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'pinyinCode', '拼音码', 'system_info', 810, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'memberCode', '会员编码', 'system_info', 820, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'platformCode', '平台编码', 'system_info', 830, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'status', '状态', 'system_info', 840, '1', NOW(), '1', NOW(), b'0', 1),
('erp_customer', 'remark', '备注', 'system_info', 850, '1', NOW(), '1', NOW(), b'0', 1),

('erp_sale_config', 'configType', '配置类型', 'base_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_config', 'name', '名称', 'base_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_config', 'code', '编码', 'base_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_config', 'sort', '排序', 'base_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_config', 'status', '状态', 'base_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_config', 'deptId', '部门', 'base_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_sale_config', 'remark', '备注', 'base_info', 70, '1', NOW(), '1', NOW(), b'0', 1)
ON DUPLICATE KEY UPDATE
  `field_label` = VALUES(`field_label`),
  `field_group` = VALUES(`field_group`),
  `sort` = VALUES(`sort`),
  `updater` = VALUES(`updater`),
  `update_time` = VALUES(`update_time`),
  `deleted` = b'0';
