-- Purchase management form field permission definitions.
-- Scope: main form fields, form detail-item columns, supplier form fields, and
-- selection modal fields used by purchase invoice/return detail picking.

CREATE TABLE IF NOT EXISTS `system_field_definition` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `module` VARCHAR(50) NOT NULL COMMENT 'Module key',
  `field_key` VARCHAR(100) NOT NULL COMMENT 'Field key',
  `field_label` VARCHAR(100) NOT NULL COMMENT 'Field label',
  `field_group` VARCHAR(50) DEFAULT NULL COMMENT 'Field group',
  `sort` INT NOT NULL DEFAULT 0 COMMENT 'Sort',
  `creator` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_module_field` (`module`, `field_key`, `tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System field definition';

CREATE TABLE IF NOT EXISTS `system_role_field_permission` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `role_id` BIGINT NOT NULL COMMENT 'Role id',
  `field_id` BIGINT NOT NULL COMMENT 'Field definition id',
  `hidden` BIT(1) NOT NULL DEFAULT b'1' COMMENT 'Whether hidden',
  `creator` VARCHAR(64) DEFAULT '',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` VARCHAR(64) DEFAULT '',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  `tenant_id` BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_field` (`role_id`, `field_id`, `tenant_id`, `deleted`),
  KEY `idx_field_id` (`field_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='System role field permission';

INSERT INTO `system_field_definition`
(`module`, `field_key`, `field_label`, `field_group`, `sort`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
('erp_purchase_order', 'no', '订单单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'orderTime', '创建时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'supplierId', '供应商', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'documentType', '单据类型', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'purchaser', '采购员', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'deptId', '部门', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'taxPercent', '税率(%)', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'orderDate', '订货日期', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'latestOrderDate', '最近订货日期', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'purchaseCycle', '采购周期', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'arrivalDate', '到货日期', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'deliveryMethod', '送货方式', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'purchaseType', '采购方式', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'settleMethod', '结算方式', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'invoiceType', '开票类型', 'main_form', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'factoryOrderNo', '厂家单号', 'main_form', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'receiveAddress', '收货地址', 'main_form', 170, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'orderFormula', '订货公式', 'main_form', 180, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'sendDate', '发出日期', 'main_form', 190, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'latestArrivalDate', '最近到货日期', 'main_form', 200, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'saleDateFrom', '销售日期从', 'main_form', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'saleDateTo', '销售日期到', 'main_form', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'remark', '备注', 'main_form', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'fileUrl', '附件', 'main_form', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'items', '采购产品清单', 'main_form', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'discountPercent', '优惠率(%)', 'main_form', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'discountPrice', '付款优惠', 'main_form', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'totalPrice', '优惠后金额', 'main_form', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'accountId', '结算账户', 'main_form', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'depositPrice', '支付订金', 'main_form', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_inStatus', '入库状态', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_gift', '赠品', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_productCode', '编码', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_warehouseId', '所属仓库', 'detail_item', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_productId', '零件名称', 'detail_item', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_count', '订货数', 'detail_item', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_productPrice', '订货价', 'detail_item', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_vehicleModel', '适用车型', 'detail_item', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_standard', '规格', 'detail_item', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_featureCode', '特征码', 'detail_item', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_productUnitName', '单位', 'detail_item', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_totalProductPrice', '订货金额', 'detail_item', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_arrivalCount', '到货数', 'detail_item', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_warehousePosition', '货架位', 'detail_item', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_drawingNo', '图号', 'detail_item', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_batchNo', '批次', 'detail_item', 360, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_factoryCode', '厂家编码', 'detail_item', 370, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_brand', '品牌', 'detail_item', 380, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_remark', '开单备注', 'detail_item', 390, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_order', 'item_supplierId', '供应商', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),

('erp_purchase_in', 'no', '入库单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'inTime', '入库时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'orderNo', '关联订单', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'supplierId', '供应商', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'accountId', '结算账户', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'remark', '备注', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'fileUrl', '附件', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'purchaser', '采购员', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'deptId', '部门', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'accountant', '记账员', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'handler', '经办人', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'items', '入库产品清单', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'totalCount', '合计数量', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'totalProductPrice', '合计金额', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'totalTaxPrice', '合计税额', 'main_form', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'totalPrice', '应付金额', 'main_form', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_warehouseId', '仓库名称', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_gift', '是否赠品', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_productId', '产品名称', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_count', '数量', 'detail_item', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_productPrice', '产品单价', 'detail_item', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_totalProductPrice', '产品金额', 'detail_item', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_adjustStatus', '调价情况', 'detail_item', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_invoiceStatus', '开票情况', 'detail_item', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_returnStatus', '退货情况', 'detail_item', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_returnCount', '已退货数量', 'detail_item', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_stockCount', '库存', 'detail_item', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_productBarCode', '条码', 'detail_item', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_productUnitName', '单位', 'detail_item', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_packageQty', '包装数', 'detail_item', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_wholeQty', '整件数', 'detail_item', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_warehousePosition', '货架位', 'detail_item', 360, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_barCode', '条形码', 'detail_item', 370, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_batchNo', '批次', 'detail_item', 380, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_drawingNo', '图号', 'detail_item', 390, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_brand', '品牌', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_vehicleModel', '适用车型', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_originPlace', '产地', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_remark', '备注', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_totalCount', '原数量', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_inCount', '已入库', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_taxPercent', '税率(%)', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_taxPrice', '税额', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_in', 'item_totalPrice', '合计金额', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),

('erp_purchase_return', 'returnMode', '退货模式', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'no', '退货单号', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'returnTime', '退货日期', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'sourceInNo', '原入库单', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'supplierId', '供应商', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'purchaser', '采购员', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'handler', '制单人', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'deptId', '部门', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'taxRate', '税率', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'invoiceType', '开票类型', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'transportMethod', '运输方式', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'settleMethod', '结算方式', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'shipArea', '发货区', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'packageCount', '件数', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'warehouseType', '仓库类型', 'main_form', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'freightType', '运费类型', 'main_form', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'freightAmount', '运费金额', 'main_form', 170, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'logisticsCompany', '物流公司', 'main_form', 180, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'logisticsNo', '物流单号', 'main_form', 190, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'sourceType', '单据来源', 'main_form', 200, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'factoryOrderNo', '厂家单号', 'main_form', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'priority', '优先级', 'main_form', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'orderMethod', '开单方式', 'main_form', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'remark', '备注', 'main_form', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'fileUrl', '附件', 'main_form', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'items', '退货产品清单', 'main_form', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_warehouseId', '仓库名称', 'detail_item', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_productCode', '产品编码', 'detail_item', 315, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_productName', '产品名称', 'detail_item', 318, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_productId', '产品名称', 'detail_item', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_count', '数量', 'detail_item', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_productPrice', '产品单价', 'detail_item', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_totalProductPrice', '产品金额', 'detail_item', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_sourceInNo', '原入库单', 'detail_item', 360, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_inCount', '原入库数量', 'detail_item', 370, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_returnableCount', '可退数量', 'detail_item', 380, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_partCode', '零件编码', 'detail_item', 390, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_partName', '零件名称', 'detail_item', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_vehicleModel', '适用车型', 'detail_item', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_originPlace', '产地', 'detail_item', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_stockCount', '库存', 'detail_item', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_productBarCode', '条码', 'detail_item', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_productUnitName', '单位', 'detail_item', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_weight', '重量', 'detail_item', 452, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_packageQty', '包装数', 'detail_item', 454, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_remark', '备注', 'detail_item', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_returnCount', '已退货', 'detail_item', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_taxPercent', '税率(%)', 'detail_item', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_taxPrice', '税额', 'detail_item', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_no', '选择入库单号', 'select_modal', 610, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_supplierName', '选择供应商', 'select_modal', 620, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_inTime', '选择入库时间', 'select_modal', 630, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_totalCount', '选择入库数量', 'select_modal', 640, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_totalPrice', '选择入库金额', 'select_modal', 650, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_orderNo', '选择来源单号', 'select_modal', 660, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_productCode', '选择产品编码', 'select_modal', 710, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_productName', '选择产品名称', 'select_modal', 720, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_lastPurchasePrice', '选择最近采购价', 'select_modal', 730, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_salePrice', '选择销售价', 'select_modal', 740, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_referencePrice', '选择参考价', 'select_modal', 750, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'select_col_retailPrice', '选择零售价', 'select_modal', 760, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_return', 'item_totalPrice', '合计金额', 'detail_item', 500, '1', NOW(), '1', NOW(), b'0', 1),

('erp_supplier', 'name', '供应商名称', 'basic_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'shortName', '简称', 'basic_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'foreignName', '外文名', 'basic_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'code', '编码', 'basic_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'oldCode', '旧编码', 'basic_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'contact', '联系人', 'basic_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'mobile', '手机号码', 'basic_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'telephone', '联系电话', 'basic_info', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'email', '电子邮箱', 'basic_info', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'fax', '传真', 'basic_info', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'remark', '备注', 'basic_info', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'region', '区域', 'category_purchase', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'category', '往来类别', 'category_purchase', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'supplierType', '供应商类型', 'category_purchase', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'purchaser', '采购员', 'category_purchase', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'companyNature', '公司性质', 'category_purchase', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'purchaseControl', '采购管控', 'category_purchase', 170, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'arrivalCycle', '到货周期', 'category_purchase', 180, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'purchaseLeadDays', '采购提前期', 'category_purchase', 190, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'obsolete', '淘汰', 'category_purchase', 200, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'obsoleteDate', '淘汰日期', 'category_purchase', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'groupSupplier', '集团供应商', 'category_purchase', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'allowBranchOrder', '允许分店开单', 'category_purchase', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'settleMethod', '结算方式', 'settle_logistics', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'settleLocked', '结算锁定', 'settle_logistics', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'transportMethod', '运输方式', 'settle_logistics', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'freightType', '运费类型', 'settle_logistics', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'logisticsCompany', '物流公司', 'settle_logistics', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'arrivalPoint', '到货点', 'settle_logistics', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'floatUpdateLastPrice', '浮动更新最近价格', 'settle_logistics', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'performanceProfitRef', '绩效利润参考依据', 'settle_logistics', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'address', '地址', 'address_info', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'areaIds', '省市区县', 'address_info', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'postalCode', '邮政编码', 'address_info', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'website', '网址', 'address_info', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'invoiceType', '开票类型', 'invoice_info', 360, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'taxpayerId', '纳税人识别号', 'invoice_info', 370, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'invoiceBank', '开票银行', 'invoice_info', 380, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'invoiceBankAccount', '开票银行账号', 'invoice_info', 390, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'invoiceAddress', '开票地址', 'invoice_info', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'invoicePhone', '开票电话', 'invoice_info', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'invoiceCompany', '开票单位', 'invoice_info', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'account', '账户', 'finance_info', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'bankName', '开户行', 'finance_info', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'bankAccount', '开户账号', 'finance_info', 450, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'bankAddress', '开户地址', 'finance_info', 460, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'taxNo', '纳税人识别号', 'finance_info', 470, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'taxPercent', '税率(%)', 'finance_info', 480, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'financePhone', '财务联系电话', 'finance_info', 490, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'memberCode', '会员编码', 'finance_info', 500, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'legalPerson', '法定代表', 'finance_info', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_supplier', 'creditCode', '统一信用代码', 'finance_info', 520, '1', NOW(), '1', NOW(), b'0', 1),

('erp_purchase_invoice', 'no', '票据单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'invoiceDate', '开票日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'supplierId', '供应商', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'invoiceType', '票据类型', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'invoiceNo', '发票号', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'invoiceCount', '发票张数', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'deptId', '部门', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'handlerId', '经手人', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'remark', '备注', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'fileUrl', '附件', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'items', '票据明细', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'taxExclusiveAmount', '不含税金额', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'taxAmount', '税额', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'totalAmount', '价税合计', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_sourceInNo', '来源入库单', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_productCode', '产品编码', 'detail_item', 215, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_productId', '产品名称', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_count', '数量', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_productPrice', '不含税单价', 'detail_item', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_taxExclusivePrice', '不含税金额', 'detail_item', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_taxPercent', '税率(%)', 'detail_item', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_taxPrice', '税额', 'detail_item', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_totalPrice', '价税合计', 'detail_item', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'select_col_no', '选择入库单号', 'select_modal', 610, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'select_col_inTime', '选择入库时间', 'select_modal', 620, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'select_col_creatorName', '选择创建人', 'select_modal', 630, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'select_col_hasInvoice', '选择已开票', 'select_modal', 640, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'select_col_totalCount', '选择合计数量', 'select_modal', 650, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'select_col_totalPrice', '选择合计金额', 'select_modal', 660, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_invoice', 'item_remark', '备注', 'detail_item', 290, '1', NOW(), '1', NOW(), b'0', 1),

('erp_purchase_price_adjust', 'no', '调价单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'adjustTime', '调价日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'adjustType', '调价方式', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'supplierId', '供应商', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'deptId', '部门', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'adjuster', '调价人', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'totalAdjustPrice', '调价总额', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'remark', '备注', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'items', '调价明细', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_inNo', '入库单号', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_productCode', '产品编码', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_productName', '产品名称', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_productUnitName', '单位', 'detail_item', 235, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_weight', '重量', 'detail_item', 236, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_packageQty', '包装数', 'detail_item', 237, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_vehicleModel', '车型', 'detail_item', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_standard', '规格', 'detail_item', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_featureCode', '特征码', 'detail_item', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_originPlace', '产地', 'detail_item', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_brand', '品牌', 'detail_item', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_drawingNo', '图号', 'detail_item', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_warehousePosition', '货架位', 'detail_item', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_count', '数量', 'detail_item', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_oldPrice', '原单价', 'detail_item', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_adjustRatio', '调价比率(%)', 'detail_item', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_newPrice', '调价后单价', 'detail_item', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_purchase_price_adjust', 'item_adjustPrice', '调价差额', 'detail_item', 350, '1', NOW(), '1', NOW(), b'0', 1)
ON DUPLICATE KEY UPDATE
  `field_label` = VALUES(`field_label`),
  `field_group` = VALUES(`field_group`),
  `sort` = VALUES(`sort`),
  `updater` = VALUES(`updater`),
  `update_time` = VALUES(`update_time`),
  `deleted` = b'0';
