-- System field permission finance v37
-- Blacklist mode: records in system_role_field_permission mean hidden fields.
-- Scope: finance form/detail fields only. List columns, list search fields, and select modal fields are intentionally not registered.

INSERT INTO `system_field_definition`
(`module`, `field_key`, `field_label`, `field_group`, `sort`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
('erp_account', 'name', '账户名称', 'base_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'accountType', '账户类型', 'base_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'no', '账户编码', 'base_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'remark', '备注', 'base_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'bankName', '开户行', 'bank_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'bankAccount', '银行账号', 'bank_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'currentBalance', '当前余额', 'bank_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'status', '启用状态', 'status_info', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'sort', '排序', 'status_info', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_account', 'defaultStatus', '是否默认', 'status_info', 100, '1', NOW(), '1', NOW(), b'0', 1),

('erp_finance_payment', 'no', '付款单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'paymentTime', '付款时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'supplierId', '供应商', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'financeUserId', '财务人员', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'remark', '备注', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'fileUrl', '附件', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'items', '付款明细', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'accountId', '付款账户', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'totalPrice', '合计付款', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'discountPrice', '优惠金额', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'paymentPrice', '实际付款', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'item_bizNo', '明细-单据编号', 'detail_item', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'item_totalPrice', '明细-应付金额', 'detail_item', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'item_paidPrice', '明细-已付金额', 'detail_item', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'item_paymentPrice', '明细-本次付款', 'detail_item', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payment', 'item_remark', '明细-备注', 'detail_item', 160, '1', NOW(), '1', NOW(), b'0', 1),

('erp_finance_receipt', 'no', '收款单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'receiptTime', '收款时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'customerId', '客户', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'financeUserId', '财务人员', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'remark', '备注', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'fileUrl', '附件', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'items', '收款明细', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'accountId', '收款账户', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'totalPrice', '合计收款', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'discountPrice', '优惠金额', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'receiptPrice', '实际收款', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'item_bizNo', '明细-单据编号', 'detail_item', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'item_totalPrice', '明细-应收金额', 'detail_item', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'item_receiptedPrice', '明细-已收金额', 'detail_item', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'item_receiptPrice', '明细-本次收款', 'detail_item', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receipt', 'item_remark', '明细-备注', 'detail_item', 160, '1', NOW(), '1', NOW(), b'0', 1),

('erp_finance_transfer', 'no', '转账单号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'transferTime', '转账时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'outAccountId', '转出账户', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'outAccountBalance', '账户余额', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'inAccountId', '转入账户', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'transferPrice', '转账金额', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'financeUserId', '财务人员', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'remark', '备注', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_transfer', 'fileUrl', '附件', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),

('erp_finance_payable_expense', 'no', '单据编号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'bizTime', '单据日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'settleMethod', '结算方式', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'accountId', '结算账户', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'voucherNo', '凭证号', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'expenseType', '费用类型', 'expense_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'totalAmount', '总金额', 'expense_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'deptId', '申请部门', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'handlerId', '申请人', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'party', '收款对象', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'relatedBiz', '相关业务', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'docType', '单据类型', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'remark', '备注', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'fileUrl', '附件', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'items', '费用明细', 'detail_item', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_itemName', '明细-费用项目', 'detail_item', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_amount', '明细-金额', 'detail_item', 170, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_invoiceNo', '明细-发票号', 'detail_item', 180, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_party', '明细-收款对象', 'detail_item', 190, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_deptId', '明细-部门', 'detail_item', 200, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_bizDate', '明细-发生日期', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_handlerId', '明细-申请人', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_qty', '明细-数量', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_expenseCategory', '明细-费用分类', 'detail_item', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_remark', '明细-备注', 'detail_item', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_expense', 'item_fileUrl', '明细-附件', 'detail_item', 260, '1', NOW(), '1', NOW(), b'0', 1),

('erp_finance_payable_other', 'no', '单据编号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'bizTime', '业务日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'supplierId', '供应商', 'payable_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'voucherNo', '凭证号', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'settledAmount', '已结金额', 'payable_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'deptId', '部门', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'payableAmount', '应付金额', 'payable_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'project', '调账项目', 'payable_info', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'sourceType', '来源类型', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'handlerId', '经手人', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'remark', '调账原因', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_other', 'fileUrl', '附件', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),

('erp_finance_receivable_other_income', 'no', '单据编号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'bizTime', '业务时间', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'settleMethod', '结算方式', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'accountId', '收款账户', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'voucherNo', '凭证号', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'incomeType', '收入类型', 'income_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'totalAmount', '收入合计', 'income_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'deptId', '部门', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'handlerId', '经手人', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'party', '往来单位', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'relatedBiz', '关联业务', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'docType', '单据类型', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'remark', '备注', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'fileUrl', '附件', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'items', '收入明细', 'detail_item', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_itemName', '明细-项目名称', 'detail_item', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_amount', '明细-收入金额', 'detail_item', 170, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_invoiceNo', '明细-发票号', 'detail_item', 180, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_party', '明细-往来单位', 'detail_item', 190, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_deptId', '明细-部门', 'detail_item', 200, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_bizDate', '明细-业务日期', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_handlerId', '明细-经手人', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_qty', '明细-数量', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_freightType', '明细-运费类型', 'detail_item', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_remark', '明细-备注', 'detail_item', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other_income', 'item_fileUrl', '明细-附件', 'detail_item', 260, '1', NOW(), '1', NOW(), b'0', 1),

('erp_finance_receivable_other', 'no', '单据编号', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'bizTime', '业务日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'customerId', '客户', 'receivable_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'voucherNo', '凭证号', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'settledAmount', '已结金额', 'receivable_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'deptId', '部门', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'receivableAmount', '应收金额', 'receivable_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'costAmount', '成本金额', 'receivable_info', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'project', '调账项目', 'receivable_info', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'sourceType', '来源类型', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'handlerId', '经手人', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'receivableType', '应收类型', 'receivable_info', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'remark', '备注', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'isPaperNote', '纸质单据', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'paperNoteDesc', '纸质单据说明', 'main_form', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'sourceNo', '来源单号', 'main_form', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_other', 'fileUrl', '附件', 'main_form', 170, '1', NOW(), '1', NOW(), b'0', 1)
ON DUPLICATE KEY UPDATE
  `field_label` = VALUES(`field_label`),
  `field_group` = VALUES(`field_group`),
  `sort` = VALUES(`sort`),
  `updater` = '1',
  `update_time` = NOW(),
  `deleted` = b'0';

INSERT INTO `system_menu`
(`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`,
 `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`)
VALUES
(31137, '设置角色字段权限', 'system:permission:assign-role-field-permission', 3, 8, 101, '', '', '', NULL,
 0, b'1', b'1', b'1', '1', NOW(), '1', NOW(), b'0')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `permission` = VALUES(`permission`),
  `type` = VALUES(`type`),
  `sort` = VALUES(`sort`),
  `parent_id` = VALUES(`parent_id`),
  `status` = VALUES(`status`),
  `visible` = VALUES(`visible`),
  `keep_alive` = VALUES(`keep_alive`),
  `always_show` = VALUES(`always_show`),
  `updater` = '1',
  `update_time` = NOW(),
  `deleted` = b'0';

INSERT IGNORE INTO `system_role_menu`
(`role_id`, `menu_id`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
(1, 31137, '1', NOW(), '1', NOW(), b'0', 1);
