-- System field permission missing modules v65
-- Blacklist mode: records in system_role_field_permission mean hidden fields.
-- Scope: modules that were present in the role permission UI but had no
-- system_field_definition rows. This script is idempotent and does not delete
-- or overwrite existing role field permission selections.

INSERT INTO `system_field_definition`
(`module`, `field_key`, `field_label`, `field_group`, `sort`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`)
VALUES
-- 系统管理 / 角色管理
('system_role', 'name', '角色名称', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'status', '角色状态', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'remark', '角色备注', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'createTime', '创建时间', 'search_info', 110, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'col_id', '列表-角色编号', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'col_name', '列表-角色名称', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'col_type', '列表-角色类型', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'col_remark', '列表-角色备注', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'col_status', '列表-角色状态', 'list_col', 250, '1', NOW(), '1', NOW(), b'0', 1),
('system_role', 'col_createTime', '列表-创建时间', 'list_col', 260, '1', NOW(), '1', NOW(), b'0', 1),

-- 库存管理 / 库存流水
('erp_stock_record', 'bizDate', '开单日期', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'bizTypes', '单据类型', 'search_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'warehouseId', '仓库', 'search_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'productId', '产品', 'search_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'productCode', '零件编码', 'search_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'productName', '零件名称', 'search_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'vehicleModel', '适用车型', 'search_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'originPlace', '产地', 'search_info', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'bizNo', '单号', 'search_info', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_bizDate', '列表-发生日期', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_bizType', '列表-交易类型', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_bizNo', '列表-单号', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_productCode', '列表-零件编码', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_productName', '列表-产品名称', 'list_col', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_categoryName', '列表-产品分类', 'list_col', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_unitName', '列表-产品单位', 'list_col', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_warehouseName', '列表-仓库', 'list_col', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_inCount', '列表-入库数', 'list_col', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_inUnitPrice', '列表-入库单价', 'list_col', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_inAmount', '列表-入库金额', 'list_col', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_outCount', '列表-出库数', 'list_col', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_outUnitPrice', '列表-出库成本单价', 'list_col', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_outAmount', '列表-出库成本金额', 'list_col', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_count', '列表-出入库数量', 'list_col', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_totalCount', '列表-结存数/库存量', 'list_col', 360, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_unitPrice', '列表-单价', 'list_col', 370, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_totalPrice', '列表-金额', 'list_col', 380, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_costPrice', '列表-结存单价', 'list_col', 390, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_costAmount', '列表-结存金额', 'list_col', 400, '1', NOW(), '1', NOW(), b'0', 1),
('erp_stock_record', 'col_creatorName', '列表-操作人', 'list_col', 410, '1', NOW(), '1', NOW(), b'0', 1),

-- 资金管理 / 应收账款
('erp_finance_receivable_account', 'customerId', '客户', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'saleUserId', '业务员', 'search_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'deptId', '部门', 'search_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'bizTime', '业务时间', 'search_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'showZeroBalance', '显示零余额', 'search_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_customerName', '列表-客户', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_contact', '列表-联系人', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_mobile', '列表-电话', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_deptName', '列表-部门', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_saleUserName', '列表-业务员', 'list_col', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_billType', '列表-单据类型', 'list_col', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_receivableAmount', '列表-应收金额', 'list_col', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_receivedAmount', '列表-已收金额', 'list_col', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_unreceivedAmount', '列表-未收余额', 'list_col', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_receiveStatus', '列表-收款状态', 'list_col', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_saleOutAmount', '列表-销售出库', 'list_col', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_saleReturnAmount', '列表-销售退货', 'list_col', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_priceAdjustAmount', '列表-销售调价', 'list_col', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_receiptAmount', '列表-收款', 'list_col', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_writeOffAmount', '列表-核销', 'list_col', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_otherReceivableAmount', '列表-其他应收', 'list_col', 360, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_receivableBalance', '列表-应收余额', 'list_col', 370, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_preAdvanceAmount', '列表-未核销预收', 'list_col', 380, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'col_lastBizTime', '列表-最近业务时间', 'list_col', 390, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_docType', '明细-单据类型', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_docDate', '明细-单据日期', 'detail_item', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_docNo', '明细-单据号', 'detail_item', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_prevBalance', '明细-上笔余额', 'detail_item', 540, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_increaseAmount', '明细-增加金额', 'detail_item', 550, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_receiptAmount', '明细-收款金额', 'detail_item', 560, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_writeOffAmount', '明细-核销金额', 'detail_item', 570, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_receivable_account', 'detail_balance', '明细-余额', 'detail_item', 580, '1', NOW(), '1', NOW(), b'0', 1),

-- 资金管理 / 应付账款
('erp_finance_payable_account', 'supplierId', '供应商', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'deptId', '部门', 'search_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'handlerId', '经手人', 'search_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'bizTime', '业务时间', 'search_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'showZeroBalance', '显示零余额', 'search_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_supplierName', '列表-供应商', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_contact', '列表-联系人', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_mobile', '列表-电话', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_deptName', '列表-部门', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_handlerName', '列表-经手人', 'list_col', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_purchaseInAmount', '列表-采购入库', 'list_col', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_purchaseReturnAmount', '列表-采购退货', 'list_col', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_priceAdjustAmount', '列表-采购调价', 'list_col', 280, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_otherPayableAmount', '列表-其他应付', 'list_col', 290, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_paymentAmount', '列表-付款', 'list_col', 300, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_writeOffAmount', '列表-核销', 'list_col', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_balance', '列表-应付余额', 'list_col', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_unclearedPrepayment', '列表-未核销预付款', 'list_col', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'col_lastBizTime', '列表-最近业务时间', 'list_col', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_docType', '明细-单据类型', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_docDate', '明细-单据日期', 'detail_item', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_docNo', '明细-单据号', 'detail_item', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_prevBalance', '明细-上笔余额', 'detail_item', 540, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_increaseAmount', '明细-增加金额', 'detail_item', 550, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_paymentAmount', '明细-减少金额', 'detail_item', 560, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_writeOffAmount', '明细-核销金额', 'detail_item', 570, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_payable_account', 'detail_balance', '明细-余额', 'detail_item', 580, '1', NOW(), '1', NOW(), b'0', 1),

-- 资金管理 / 应收冲应付
('erp_finance_settlement_offset', 'subjectName', '往来对象', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'bizTime', '业务时间', 'search_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'deptId', '所属部门', 'search_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'showZeroBalance', '显示零余额', 'search_info', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'col_subjectName', '列表-往来对象', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'col_deptName', '列表-所属部门', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'col_contact', '列表-联系人', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'col_mobile', '列表-电话', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'col_receivableBalance', '列表-应收余额', 'list_col', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'col_payableBalance', '列表-应付余额', 'list_col', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'col_offsetBalance', '列表-轧抵余额', 'list_col', 270, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_docType', '明细-单据类型', 'detail_item', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_docDate', '明细-单据日期', 'detail_item', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_docNo', '明细-单据号', 'detail_item', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_prevBalance', '明细-上笔余额', 'detail_item', 540, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_increaseAmount', '明细-增加金额', 'detail_item', 550, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_receiptAmount', '明细-应收减少金额', 'detail_item', 560, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_paymentAmount', '明细-应付减少金额', 'detail_item', 570, '1', NOW(), '1', NOW(), b'0', 1),
('erp_finance_settlement_offset', 'detail_balance', '明细-余额', 'detail_item', 580, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 会计科目
('erp_accounting_subject', 'subjectCode', '科目编码', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'subjectName', '科目名称', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'shortName', '科目别名', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'subjectCategory', '科目类型', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'voucherType', '凭证类型', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'parentCode', '父科目编码', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'balanceDirection', '余额方向', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'openingBalance', '期初余额', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'enable', '是否启用', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'auxiliaryTypes', '辅助核算', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_subject', 'remark', '备注', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 系统开账
('erp_accounting_book_open', 'no', '开账编号', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'fiscalYear', '会计年度', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'period', '开账期间', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'startDate', '开始时间', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'opened', '是否开账', 'search_info', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'col_no', '列表-开账编号', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'col_fiscalYear', '列表-会计年度', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'col_period', '列表-开账期间', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'col_startDate', '列表-期间开始时间', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'col_opened', '列表-是否开账', 'list_col', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'col_operateTime', '列表-操作时间', 'list_col', 260, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_book_open', 'col_operator', '列表-操作人', 'list_col', 270, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 凭证列表
('erp_accounting_voucher', 'voucherWord', '凭证字', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'voucherNo', '凭证编号', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'voucherDate', '凭证日期/制单日期', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'attachmentCount', '附件张数', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'summary', '摘要', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'bookkeeperUserId', '记账', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'cashierUserId', '出纳', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'supervisorUserId', '主管', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'auditorUserId', '审核', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'makerUserId', '制单人', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'auditStatus', '审核状态', 'search_info', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'generateBusinessDoc', '是否产生业务单据', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'bizDocType', '业务单据类型', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'remark', '备注', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'item_summary', '分录-摘要', 'detail_item', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'item_subjectId', '分录-会计科目', 'detail_item', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'item_auxiliaryName', '分录-核算项', 'detail_item', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'item_debitAmount', '分录-借方金额', 'detail_item', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'item_creditAmount', '分录-贷方金额', 'detail_item', 350, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_voucherDate', '列表-制单日期', 'list_col', 510, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_voucherNo', '列表-凭证编号', 'list_col', 520, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_summary', '列表-摘要', 'list_col', 530, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_sourceBizAmount', '列表-业务金额', 'list_col', 540, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_totalDebit', '列表-借方金额合计', 'list_col', 550, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_totalCredit', '列表-贷方金额合计', 'list_col', 560, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_makerUserName', '列表-制单人', 'list_col', 570, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_auditorUserName', '列表-审核人', 'list_col', 580, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_auditTime', '列表-审核日期', 'list_col', 590, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher', 'col_auditStatus', '列表-状态', 'list_col', 600, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 凭证生成
('erp_accounting_voucher_attribution', 'sourceBizType', '单据类型', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'bizType', '业务单据类型', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'bizNo', '业务单号', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'bizDate', '业务发生日期', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'bizAmount', '原始金额', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'discountAmount', '折让金额', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'receivedAmount', '实收金额', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'voucherMakeDate', '制单日期', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'attributionYear', '归属年', 'main_form', 90, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'attributionMonth', '归属月', 'main_form', 100, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'transactionParty', '交易单位', 'main_form', 110, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'settleMethod', '结算方式', 'main_form', 120, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'shippingMethod', '运输方式', 'main_form', 130, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'receivableConfirmed', '应收确认', 'main_form', 140, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'invoiceIssued', '是否开票', 'main_form', 150, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'shipStatus', '发货状态', 'main_form', 160, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'summary', '摘要', 'main_form', 170, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'remark', '备注', 'main_form', 180, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'partyName', '交易单位', 'search_info', 190, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'col_bizNo', '列表-单据编号', 'list_col', 310, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'col_bizDate', '列表-业务日期', 'list_col', 320, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'col_bizAmount', '列表-原始金额', 'list_col', 330, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'col_transactionParty', '列表-交易单位', 'list_col', 340, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_attribution', 'col_attributionStatus', '列表-归属状态', 'list_col', 350, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 凭证字
('erp_accounting_voucher_word', 'code', '凭证字代码', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'name', '名称', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'enable', '是否启用', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'sort', '排序', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'remark', '备注', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'col_code', '列表-凭证字代码', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'col_name', '列表-名称', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'col_enable', '列表-是否启用', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'col_sort', '列表-排序', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'col_remark', '列表-备注', 'list_col', 250, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_voucher_word', 'col_createTime', '列表-创建时间', 'list_col', 260, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 报表
('erp_accounting_balance_sheet', 'filterMonth', '日期', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_balance_sheet', 'company', '编制单位', 'search_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_balance_sheet', 'col_itemName', '列表-项目', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_balance_sheet', 'col_rowNo', '列表-行次', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_balance_sheet', 'col_beginAmount', '列表-期初余额', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_balance_sheet', 'col_endAmount', '列表-期末余额', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_income_statement', 'filterMonth', '日期', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_income_statement', 'company', '编制单位', 'search_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_income_statement', 'includeChainTransfer', '包含连锁调拨利润', 'search_info', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_income_statement', 'col_itemName', '列表-项目', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_income_statement', 'col_rowNo', '列表-行次', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_income_statement', 'col_monthAmount', '列表-本月数', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_income_statement', 'col_yearAmount', '列表-本年累计', 'list_col', 240, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_cash_flow', 'filterMonth', '日期', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_cash_flow', 'company', '编制单位', 'search_info', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_cash_flow', 'col_itemName', '列表-项目/补充资料', 'list_col', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_cash_flow', 'col_rowNo', '列表-行次', 'list_col', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_cash_flow', 'col_currentAmount', '列表-本期金额', 'list_col', 230, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 其他应收单
('erp_accounting_other_receivable', 'no', '单据编号', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'bizTime', '业务日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'partyType', '对方类型', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'partyName', '对方名称', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'accountId', '结算账户', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'status', '审核状态', 'search_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'remark', '备注', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'item_summary', '明细-摘要', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'item_amount', '明细-金额', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'item_remark', '明细-备注', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'col_no', '列表-单据编号', 'list_col', 410, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'col_totalAmount', '列表-合计金额', 'list_col', 420, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'col_discountAmount', '列表-折让金额', 'list_col', 430, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'col_actualAmount', '列表-实际金额', 'list_col', 440, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_receivable', 'col_createTime', '列表-创建时间', 'list_col', 450, '1', NOW(), '1', NOW(), b'0', 1),

-- 财务核算 / 预收款单、预付款单、预收账款单、其他应付单
('erp_accounting_pre_receipt', 'no', '单据编号', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'bizTime', '业务日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'partyType', '对方类型', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'partyName', '对方名称', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'accountId', '结算账户', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'discountAmount', '折让金额', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'status', '审核状态', 'search_info', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'remark', '备注', 'main_form', 80, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'item_summary', '明细-摘要', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'item_amount', '明细-金额', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receipt', 'item_remark', '明细-备注', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'no', '单据编号', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'bizTime', '业务日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'partyType', '对方类型', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'partyName', '对方名称', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'accountId', '结算账户', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'status', '审核状态', 'search_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'remark', '备注', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'item_summary', '明细-摘要', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'item_amount', '明细-金额', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_payment', 'item_remark', '明细-备注', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'no', '单据编号', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'bizTime', '业务日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'partyType', '对方类型', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'partyName', '对方名称', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'accountId', '结算账户', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'status', '审核状态', 'search_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'remark', '备注', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'item_summary', '明细-摘要', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'item_amount', '明细-金额', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_pre_receivable', 'item_remark', '明细-备注', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'no', '单据编号', 'search_info', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'bizTime', '业务日期', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'partyType', '对方类型', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'partyName', '对方名称', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'accountId', '结算账户', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'status', '审核状态', 'search_info', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'remark', '备注', 'main_form', 70, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'item_summary', '明细-摘要', 'detail_item', 210, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'item_amount', '明细-金额', 'detail_item', 220, '1', NOW(), '1', NOW(), b'0', 1),
('erp_accounting_other_payable', 'item_remark', '明细-备注', 'detail_item', 230, '1', NOW(), '1', NOW(), b'0', 1),

-- ERP 系统配置 / 字段配置、搜索字段配置
('erp_system_field_config', 'module', '模块', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_field_config', 'fieldName', '字段名称', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_field_config', 'fieldLabel', '字段标签', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_field_config', 'required', '是否必填', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_field_config', 'visible', '是否显示', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_field_config', 'sort', '排序', 'main_form', 60, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_search_field_config', 'module', '模块', 'main_form', 10, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_search_field_config', 'fieldName', '字段名称', 'main_form', 20, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_search_field_config', 'fieldLabel', '字段标签', 'main_form', 30, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_search_field_config', 'visible', '是否显示', 'main_form', 40, '1', NOW(), '1', NOW(), b'0', 1),
('erp_system_search_field_config', 'sort', '排序', 'main_form', 50, '1', NOW(), '1', NOW(), b'0', 1)
ON DUPLICATE KEY UPDATE
  `field_label` = VALUES(`field_label`),
  `field_group` = VALUES(`field_group`),
  `sort` = VALUES(`sort`),
  `updater` = '1',
  `update_time` = NOW(),
  `deleted` = b'0';
